#include "mach.h"
/*
 * IDENTIFICATION:
 * stub generated by bootstrap_cmds-138
 * OPTIONS: 
 */

/* Module auth */

#define	__MIG_check__Request__auth_subsystem__ 1

#include "authServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xauth_getids
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xauth_makeauth
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xauth_user_authenticate
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xauth_server_authenticate
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__auth_subsystem__
#if !defined(__MIG_check__Request__auth_getids_t__defined)
#define __MIG_check__Request__auth_getids_t__defined

mig_internal kern_return_t __MIG_check__Request__auth_getids_t(__attribute__((__unused__)) __Request__auth_getids_t *In0P)
{

	typedef __Request__auth_getids_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__auth_getids_t__defined) */
#endif /* __MIG_check__Request__auth_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine auth_getids */
mig_internal novalue _Xauth_getids
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__auth_getids_t Reply __attribute__((unused));
	typedef __Request__auth_getids_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__auth_getids_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__auth_getids_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t euidsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t auidsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t egidsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t agidsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(25000, "auth_getids")
	__BeforeRcvRpc(25000, "auth_getids")

#if	defined(__MIG_check__Request__auth_getids_t__defined)
	check_result = __MIG_check__Request__auth_getids_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__auth_getids_t__defined) */

#if	UseStaticTemplates
	OutP->euids = euidsTemplate;
#else	/* UseStaticTemplates */
	OutP->euids.deallocate =  FALSE;
	OutP->euids.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->euids.pad1 = 0;
	OutP->euids.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->euids.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->auids = auidsTemplate;
#else	/* UseStaticTemplates */
	OutP->auids.deallocate =  FALSE;
	OutP->auids.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->auids.pad1 = 0;
	OutP->auids.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->auids.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->egids = egidsTemplate;
#else	/* UseStaticTemplates */
	OutP->egids.deallocate =  FALSE;
	OutP->egids.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->egids.pad1 = 0;
	OutP->egids.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->egids.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->agids = agidsTemplate;
#else	/* UseStaticTemplates */
	OutP->agids.deallocate =  FALSE;
	OutP->agids.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->agids.pad1 = 0;
	OutP->agids.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->agids.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->euidsCnt = 0;

	OutP->auidsCnt = 0;

	OutP->egidsCnt = 0;

	OutP->agidsCnt = 0;

	RetCode = auth_getids(In0P->Head.msgh_request_port, (idarray_t *)&(OutP->euids.address), &OutP->euidsCnt, (idarray_t *)&(OutP->auids.address), &OutP->auidsCnt, (idarray_t *)&(OutP->egids.address), &OutP->egidsCnt, (idarray_t *)&(OutP->agids.address), &OutP->agidsCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->euids.size = OutP->euidsCnt * 4;

	OutP->auids.size = OutP->auidsCnt * 4;

	OutP->egids.size = OutP->egidsCnt * 4;

	OutP->agids.size = OutP->agidsCnt * 4;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 4;
	__AfterRcvRpc(25000, "auth_getids")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__auth_subsystem__
#if !defined(__MIG_check__Request__auth_makeauth_t__defined)
#define __MIG_check__Request__auth_makeauth_t__defined

mig_internal kern_return_t __MIG_check__Request__auth_makeauth_t(__attribute__((__unused__)) __Request__auth_makeauth_t *In0P)
{

	typedef __Request__auth_makeauth_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 5) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->other_handles.type != MACH_MSG_OOL_PORTS_DESCRIPTOR ||
	    In0P->other_handles.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->euids.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->auids.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->egids.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->agids.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->other_handles.count != In0P->other_handlesCnt)
		return MIG_TYPE_ERROR;
	if (In0P->euids.size / 4 != In0P->euidsCnt)
		return MIG_TYPE_ERROR;
	if (In0P->auids.size / 4 != In0P->auidsCnt)
		return MIG_TYPE_ERROR;
	if (In0P->egids.size / 4 != In0P->egidsCnt)
		return MIG_TYPE_ERROR;
	if (In0P->agids.size / 4 != In0P->agidsCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__auth_makeauth_t__defined) */
#endif /* __MIG_check__Request__auth_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine auth_makeauth */
mig_internal novalue _Xauth_makeauth
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_ports_descriptor_t other_handles;
		mach_msg_ool_descriptor_t euids;
		mach_msg_ool_descriptor_t auids;
		mach_msg_ool_descriptor_t egids;
		mach_msg_ool_descriptor_t agids;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t other_handlesCnt;
		mach_msg_type_number_t euidsCnt;
		mach_msg_type_number_t auidsCnt;
		mach_msg_type_number_t egidsCnt;
		mach_msg_type_number_t agidsCnt;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__auth_makeauth_t Reply __attribute__((unused));
	typedef __Request__auth_makeauth_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__auth_makeauth_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__auth_makeauth_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t newhandleTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		20,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(25001, "auth_makeauth")
	__BeforeRcvRpc(25001, "auth_makeauth")

#if	defined(__MIG_check__Request__auth_makeauth_t__defined)
	check_result = __MIG_check__Request__auth_makeauth_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__auth_makeauth_t__defined) */

#if	UseStaticTemplates
	OutP->newhandle = newhandleTemplate;
#else	/* UseStaticTemplates */
	OutP->newhandle.disposition = 20;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->newhandle.pad1 = 0;
#endif
	OutP->newhandle.pad2 = 0;
	OutP->newhandle.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->newhandle.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = auth_makeauth(In0P->Head.msgh_request_port, (portarray_t)(In0P->other_handles.address), In0P->other_handles.count, (idarray_t)(In0P->euids.address), In0P->euids.size / 4, (idarray_t)(In0P->auids.address), In0P->auids.size / 4, (idarray_t)(In0P->egids.address), In0P->egids.size / 4, (idarray_t)(In0P->agids.address), In0P->agids.size / 4, &OutP->newhandle.name);
	mig_deallocate((vm_offset_t) In0P->agids.address, In0P->agids.size);
	In0P->agids.address = (void *) 0;
	In0P->agids.size = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->egids.address, In0P->egids.size);
	In0P->egids.address = (void *) 0;
	In0P->egids.size = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->auids.address, In0P->auids.size);
	In0P->auids.address = (void *) 0;
	In0P->auids.size = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->euids.address, In0P->euids.size);
	In0P->euids.address = (void *) 0;
	In0P->euids.size = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->other_handles.address, 4 * In0P->other_handles.count);
	In0P->other_handles.address = (void *) 0;
	In0P->other_handles.count = (mach_msg_size_t) 0;
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(25001, "auth_makeauth")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__auth_subsystem__
#if !defined(__MIG_check__Request__auth_user_authenticate_t__defined)
#define __MIG_check__Request__auth_user_authenticate_t__defined

mig_internal kern_return_t __MIG_check__Request__auth_user_authenticate_t(__attribute__((__unused__)) __Request__auth_user_authenticate_t *In0P)
{

	typedef __Request__auth_user_authenticate_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->rendezvous.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->rendezvous.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__auth_user_authenticate_t__defined) */
#endif /* __MIG_check__Request__auth_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine auth_user_authenticate */
mig_internal novalue _Xauth_user_authenticate
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t rendezvous;
		/* end of the kernel processed data */
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__auth_user_authenticate_t Reply __attribute__((unused));
	typedef __Request__auth_user_authenticate_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__auth_user_authenticate_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__auth_user_authenticate_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t newportTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(25002, "auth_user_authenticate")
	__BeforeRcvRpc(25002, "auth_user_authenticate")

#if	defined(__MIG_check__Request__auth_user_authenticate_t__defined)
	check_result = __MIG_check__Request__auth_user_authenticate_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__auth_user_authenticate_t__defined) */

#if	UseStaticTemplates
	OutP->newport = newportTemplate;
#else	/* UseStaticTemplates */
	OutP->newport.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->newport.pad1 = 0;
#endif
	OutP->newport.pad2 = 0;
	OutP->newport.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->newport.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = auth_user_authenticate(In0P->Head.msgh_request_port, In0P->rendezvous.name, &OutP->newport.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(25002, "auth_user_authenticate")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__auth_subsystem__
#if !defined(__MIG_check__Request__auth_server_authenticate_t__defined)
#define __MIG_check__Request__auth_server_authenticate_t__defined

mig_internal kern_return_t __MIG_check__Request__auth_server_authenticate_t(__attribute__((__unused__)) __Request__auth_server_authenticate_t *In0P)
{

	typedef __Request__auth_server_authenticate_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 2) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->rendezvous.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->rendezvous.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->newport.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->newport.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__auth_server_authenticate_t__defined) */
#endif /* __MIG_check__Request__auth_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine auth_server_authenticate */
mig_internal novalue _Xauth_server_authenticate
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t rendezvous;
		mach_msg_port_descriptor_t newport;
		/* end of the kernel processed data */
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__auth_server_authenticate_t Reply __attribute__((unused));
	typedef __Request__auth_server_authenticate_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__auth_server_authenticate_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__auth_server_authenticate_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t euidsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t auidsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t egidsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t agidsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(25003, "auth_server_authenticate")
	__BeforeRcvRpc(25003, "auth_server_authenticate")

#if	defined(__MIG_check__Request__auth_server_authenticate_t__defined)
	check_result = __MIG_check__Request__auth_server_authenticate_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__auth_server_authenticate_t__defined) */

#if	UseStaticTemplates
	OutP->euids = euidsTemplate;
#else	/* UseStaticTemplates */
	OutP->euids.deallocate =  FALSE;
	OutP->euids.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->euids.pad1 = 0;
	OutP->euids.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->euids.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->auids = auidsTemplate;
#else	/* UseStaticTemplates */
	OutP->auids.deallocate =  FALSE;
	OutP->auids.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->auids.pad1 = 0;
	OutP->auids.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->auids.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->egids = egidsTemplate;
#else	/* UseStaticTemplates */
	OutP->egids.deallocate =  FALSE;
	OutP->egids.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->egids.pad1 = 0;
	OutP->egids.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->egids.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->agids = agidsTemplate;
#else	/* UseStaticTemplates */
	OutP->agids.deallocate =  FALSE;
	OutP->agids.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->agids.pad1 = 0;
	OutP->agids.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->agids.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->euidsCnt = 0;

	OutP->auidsCnt = 0;

	OutP->egidsCnt = 0;

	OutP->agidsCnt = 0;

	RetCode = auth_server_authenticate(In0P->Head.msgh_request_port, In0P->rendezvous.name, In0P->newport.name, (idarray_t *)&(OutP->euids.address), &OutP->euidsCnt, (idarray_t *)&(OutP->auids.address), &OutP->auidsCnt, (idarray_t *)&(OutP->egids.address), &OutP->egidsCnt, (idarray_t *)&(OutP->agids.address), &OutP->agidsCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->euids.size = OutP->euidsCnt * 4;

	OutP->auids.size = OutP->auidsCnt * 4;

	OutP->egids.size = OutP->egidsCnt * 4;

	OutP->agids.size = OutP->agidsCnt * 4;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 4;
	__AfterRcvRpc(25003, "auth_server_authenticate")
}



/* Description of this subsystem, for use in direct RPC */
const struct auth_subsystem auth_subsystem = {
	auth_server_routine,
	25000,
	25004,
	(mach_msg_size_t)sizeof(union __ReplyUnion__auth_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xauth_getids, 9, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__auth_getids_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xauth_makeauth, 12, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__auth_makeauth_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xauth_user_authenticate, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__auth_user_authenticate_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xauth_server_authenticate, 11, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__auth_server_authenticate_t)},
	}
};

mig_external boolean_t auth_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 25003) || (InHeadP->msgh_id < 25000) ||
	    ((routine = auth_subsystem.routine[InHeadP->msgh_id - 25000].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t auth_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 25000;

	if ((msgh_id > 3) || (msgh_id < 0))
		return 0;

	return auth_subsystem.routine[msgh_id].stub_routine;
}
