/*
 * IDENTIFICATION:
 * stub generated by bootstrap_cmds-138
 * OPTIONS: 
 */
#define	__MIG_check__Reply__exec_subsystem__ 1

#include "exec.h"

/* TODO: #include <mach/mach.h> */
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
extern void mach_msg_destroy(mach_msg_header_t *);
#ifdef __cplusplus
}
#endif /* __cplusplus */

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__MachMsgErrorWithTimeout
#define	__MachMsgErrorWithTimeout(_R_) { \
	switch (_R_) { \
	case MACH_SEND_INVALID_DATA: \
	case MACH_SEND_INVALID_DEST: \
	case MACH_SEND_INVALID_HEADER: \
		mig_put_reply_port(InP->Head.msgh_reply_port); \
		break; \
	case MACH_SEND_TIMED_OUT: \
	case MACH_RCV_TIMED_OUT: \
	default: \
		mig_dealloc_reply_port(InP->Head.msgh_reply_port); \
	} \
}
#endif	/* __MachMsgErrorWithTimeout */

#ifndef	__MachMsgErrorWithoutTimeout
#define	__MachMsgErrorWithoutTimeout(_R_) { \
	switch (_R_) { \
	case MACH_SEND_INVALID_DATA: \
	case MACH_SEND_INVALID_DEST: \
	case MACH_SEND_INVALID_HEADER: \
		mig_put_reply_port(InP->Head.msgh_reply_port); \
		break; \
	default: \
		mig_dealloc_reply_port(InP->Head.msgh_reply_port); \
	} \
}
#endif	/* __MachMsgErrorWithoutTimeout */

#ifndef	__DeclareSendRpc
#define	__DeclareSendRpc(_NUM_, _NAME_)
#endif	/* __DeclareSendRpc */

#ifndef	__BeforeSendRpc
#define	__BeforeSendRpc(_NUM_, _NAME_)
#endif	/* __BeforeSendRpc */

#ifndef	__AfterSendRpc
#define	__AfterSendRpc(_NUM_, _NAME_)
#endif	/* __AfterSendRpc */

#ifndef	__DeclareSendSimple
#define	__DeclareSendSimple(_NUM_, _NAME_)
#endif	/* __DeclareSendSimple */

#ifndef	__BeforeSendSimple
#define	__BeforeSendSimple(_NUM_, _NAME_)
#endif	/* __BeforeSendSimple */

#ifndef	__AfterSendSimple
#define	__AfterSendSimple(_NUM_, _NAME_)
#endif	/* __AfterSendSimple */

#define msgh_request_port	msgh_remote_port
#define msgh_reply_port		msgh_local_port



#if ( __MigTypeCheck )
#if __MIG_check__Reply__exec_subsystem__
#if !defined(__MIG_check__Reply__exec_exec_t__defined)
#define __MIG_check__Reply__exec_exec_t__defined

mig_internal kern_return_t __MIG_check__Reply__exec_exec_t(__Reply__exec_exec_t *Out0P)
{

	typedef __Reply__exec_exec_t __Reply __attribute__((unused));
	if (Out0P->Head.msgh_id != 26100) {
	    if (Out0P->Head.msgh_id == MACH_NOTIFY_SEND_ONCE)
		{ return MIG_SERVER_DIED; }
	    else
		{ return MIG_REPLY_MISMATCH; }
	}

#if	__MigTypeCheck
	if ((Out0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (Out0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Reply)))
		{ return MIG_TYPE_ERROR ; }
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (Out0P->Head.msgh_request_port != MACH_PORT_NULL) {
		return MIG_TYPE_ERROR;
	}
#endif	/* __MigTypeCheck */
	{
		return Out0P->RetCode;
	}
}
#endif /* !defined(__MIG_check__Reply__exec_exec_t__defined) */
#endif /* __MIG_check__Reply__exec_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine exec_exec */
mig_external kern_return_t exec_exec
(
	exec_t execserver,
	file_t file,
	mach_port_t oldtask,
	int flags,
	data_t argv,
	mach_msg_type_number_t argvCnt,
	data_t envp,
	mach_msg_type_number_t envpCnt,
	portarray_t dtable,
	mach_msg_type_number_t dtableCnt,
	portarray_t portarray,
	mach_msg_type_number_t portarrayCnt,
	intarray_t intarray,
	mach_msg_type_number_t intarrayCnt,
	portarray_t deallocnames,
	mach_msg_type_number_t deallocnamesCnt,
	portarray_t destroynames,
	mach_msg_type_number_t destroynamesCnt
)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t file;
		mach_msg_port_descriptor_t oldtask;
		mach_msg_ool_descriptor_t argv;
		mach_msg_ool_descriptor_t envp;
		mach_msg_ool_ports_descriptor_t dtable;
		mach_msg_ool_ports_descriptor_t portarray;
		mach_msg_ool_descriptor_t intarray;
		mach_msg_ool_ports_descriptor_t deallocnames;
		mach_msg_ool_ports_descriptor_t destroynames;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int flags;
		mach_msg_type_number_t argvCnt;
		mach_msg_type_number_t envpCnt;
		mach_msg_type_number_t dtableCnt;
		mach_msg_type_number_t portarrayCnt;
		mach_msg_type_number_t intarrayCnt;
		mach_msg_type_number_t deallocnamesCnt;
		mach_msg_type_number_t destroynamesCnt;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		mach_msg_trailer_t trailer;
	} Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
		Reply Out;
	} Mess;

	Request *InP = &Mess.In;
	Reply *Out0P = &Mess.Out;

	mach_msg_return_t msg_result;

#ifdef	__MIG_check__Reply__exec_exec_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__exec_exec_t__defined */

	__DeclareSendRpc(26000, "exec_exec")

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t fileTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t oldtaskTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t argvTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t envpTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_ports_descriptor_t dtableTemplate = {
		/* addr = */		(void *)0,
		/* coun = */		0,
		/* deal = */		FALSE,
		/* copy is meaningful only in overwrite mode */
		/* copy = */		MACH_MSG_PHYSICAL_COPY,
		/* disp = */		19,
		/* type = */		MACH_MSG_OOL_PORTS_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_ports_descriptor_t portarrayTemplate = {
		/* addr = */		(void *)0,
		/* coun = */		0,
		/* deal = */		FALSE,
		/* copy is meaningful only in overwrite mode */
		/* copy = */		MACH_MSG_PHYSICAL_COPY,
		/* disp = */		19,
		/* type = */		MACH_MSG_OOL_PORTS_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t intarrayTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_ports_descriptor_t deallocnamesTemplate = {
		/* addr = */		(void *)0,
		/* coun = */		0,
		/* deal = */		FALSE,
		/* copy is meaningful only in overwrite mode */
		/* copy = */		MACH_MSG_PHYSICAL_COPY,
		/* disp = */		19,
		/* type = */		MACH_MSG_OOL_PORTS_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_ports_descriptor_t destroynamesTemplate = {
		/* addr = */		(void *)0,
		/* coun = */		0,
		/* deal = */		FALSE,
		/* copy is meaningful only in overwrite mode */
		/* copy = */		MACH_MSG_PHYSICAL_COPY,
		/* disp = */		19,
		/* type = */		MACH_MSG_OOL_PORTS_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	InP->msgh_body.msgh_descriptor_count = 9;
#if	UseStaticTemplates
	InP->file = fileTemplate;
	InP->file.name = file;
#else	/* UseStaticTemplates */
	InP->file.name = file;
	InP->file.disposition = 19;
	InP->file.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	InP->oldtask = oldtaskTemplate;
	InP->oldtask.name = oldtask;
#else	/* UseStaticTemplates */
	InP->oldtask.name = oldtask;
	InP->oldtask.disposition = 19;
	InP->oldtask.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	InP->argv = argvTemplate;
	InP->argv.address = (void *)(argv);
	InP->argv.size = argvCnt;
#else	/* UseStaticTemplates */
	InP->argv.address = (void *)(argv);
	InP->argv.size = argvCnt;
	InP->argv.deallocate =  FALSE;
	InP->argv.copy = MACH_MSG_VIRTUAL_COPY;
	InP->argv.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	InP->envp = envpTemplate;
	InP->envp.address = (void *)(envp);
	InP->envp.size = envpCnt;
#else	/* UseStaticTemplates */
	InP->envp.address = (void *)(envp);
	InP->envp.size = envpCnt;
	InP->envp.deallocate =  FALSE;
	InP->envp.copy = MACH_MSG_VIRTUAL_COPY;
	InP->envp.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	InP->dtable = dtableTemplate;
	InP->dtable.address = (void *)(dtable);
	InP->dtable.count = dtableCnt;
#else	/* UseStaticTemplates */
	InP->dtable.address = (void *)(dtable);
	InP->dtable.count = dtableCnt;
	InP->dtable.disposition = 19;
	InP->dtable.deallocate =  FALSE;
	InP->dtable.type = MACH_MSG_OOL_PORTS_DESCRIPTOR;
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	InP->portarray = portarrayTemplate;
	InP->portarray.address = (void *)(portarray);
	InP->portarray.count = portarrayCnt;
#else	/* UseStaticTemplates */
	InP->portarray.address = (void *)(portarray);
	InP->portarray.count = portarrayCnt;
	InP->portarray.disposition = 19;
	InP->portarray.deallocate =  FALSE;
	InP->portarray.type = MACH_MSG_OOL_PORTS_DESCRIPTOR;
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	InP->intarray = intarrayTemplate;
	InP->intarray.address = (void *)(intarray);
	InP->intarray.size = intarrayCnt * 4;
#else	/* UseStaticTemplates */
	InP->intarray.address = (void *)(intarray);
	InP->intarray.size = intarrayCnt * 4;
	InP->intarray.deallocate =  FALSE;
	InP->intarray.copy = MACH_MSG_VIRTUAL_COPY;
	InP->intarray.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	InP->deallocnames = deallocnamesTemplate;
	InP->deallocnames.address = (void *)(deallocnames);
	InP->deallocnames.count = deallocnamesCnt;
#else	/* UseStaticTemplates */
	InP->deallocnames.address = (void *)(deallocnames);
	InP->deallocnames.count = deallocnamesCnt;
	InP->deallocnames.disposition = 19;
	InP->deallocnames.deallocate =  FALSE;
	InP->deallocnames.type = MACH_MSG_OOL_PORTS_DESCRIPTOR;
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	InP->destroynames = destroynamesTemplate;
	InP->destroynames.address = (void *)(destroynames);
	InP->destroynames.count = destroynamesCnt;
#else	/* UseStaticTemplates */
	InP->destroynames.address = (void *)(destroynames);
	InP->destroynames.count = destroynamesCnt;
	InP->destroynames.disposition = 19;
	InP->destroynames.deallocate =  FALSE;
	InP->destroynames.type = MACH_MSG_OOL_PORTS_DESCRIPTOR;
#endif	/* UseStaticTemplates */


	InP->NDR = NDR_record;

	InP->flags = flags;

	InP->argvCnt = argvCnt;

	InP->envpCnt = envpCnt;

	InP->dtableCnt = dtableCnt;

	InP->portarrayCnt = portarrayCnt;

	InP->intarrayCnt = intarrayCnt;

	InP->deallocnamesCnt = deallocnamesCnt;

	InP->destroynamesCnt = destroynamesCnt;

	InP->Head.msgh_reply_port = mig_get_reply_port();
	InP->Head.msgh_bits = MACH_MSGH_BITS_COMPLEX|
		MACH_MSGH_BITS(19, MACH_MSG_TYPE_MAKE_SEND_ONCE);
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = execserver;
	InP->Head.msgh_id = 26000;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendRpc(26000, "exec_exec")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_RCV_MSG|MACH_MSG_OPTION_NONE, (mach_msg_size_t)sizeof(Request), (mach_msg_size_t)sizeof(Reply), InP->Head.msgh_reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendRpc(26000, "exec_exec")
	if (msg_result != MACH_MSG_SUCCESS) {
		__MachMsgErrorWithoutTimeout(msg_result);
	}
	if (msg_result != MACH_MSG_SUCCESS) {
		{ return msg_result; }
	}


#if	defined(__MIG_check__Reply__exec_exec_t__defined)
	check_result = __MIG_check__Reply__exec_exec_t((__Reply__exec_exec_t *)Out0P);
	if (check_result != MACH_MSG_SUCCESS) {
		mach_msg_destroy(&Out0P->Head);
		{ return check_result; }
	}
#endif	/* defined(__MIG_check__Reply__exec_exec_t__defined) */

	return KERN_SUCCESS;
}

#if ( __MigTypeCheck )
#if __MIG_check__Reply__exec_subsystem__
#if !defined(__MIG_check__Reply__exec_setexecdata_t__defined)
#define __MIG_check__Reply__exec_setexecdata_t__defined

mig_internal kern_return_t __MIG_check__Reply__exec_setexecdata_t(__Reply__exec_setexecdata_t *Out0P)
{

	typedef __Reply__exec_setexecdata_t __Reply __attribute__((unused));
	if (Out0P->Head.msgh_id != 26101) {
	    if (Out0P->Head.msgh_id == MACH_NOTIFY_SEND_ONCE)
		{ return MIG_SERVER_DIED; }
	    else
		{ return MIG_REPLY_MISMATCH; }
	}

#if	__MigTypeCheck
	if ((Out0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (Out0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Reply)))
		{ return MIG_TYPE_ERROR ; }
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (Out0P->Head.msgh_request_port != MACH_PORT_NULL) {
		return MIG_TYPE_ERROR;
	}
#endif	/* __MigTypeCheck */
	{
		return Out0P->RetCode;
	}
}
#endif /* !defined(__MIG_check__Reply__exec_setexecdata_t__defined) */
#endif /* __MIG_check__Reply__exec_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine exec_setexecdata */
mig_external kern_return_t exec_setexecdata
(
	exec_t execserver,
	portarray_t ports,
	mach_msg_type_number_t portsCnt,
	intarray_t ints,
	mach_msg_type_number_t intsCnt
)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_ports_descriptor_t ports;
		mach_msg_ool_descriptor_t ints;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t portsCnt;
		mach_msg_type_number_t intsCnt;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		mach_msg_trailer_t trailer;
	} Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
		Reply Out;
	} Mess;

	Request *InP = &Mess.In;
	Reply *Out0P = &Mess.Out;

	mach_msg_return_t msg_result;

#ifdef	__MIG_check__Reply__exec_setexecdata_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__exec_setexecdata_t__defined */

	__DeclareSendRpc(26001, "exec_setexecdata")

#if	UseStaticTemplates
	const static mach_msg_ool_ports_descriptor_t portsTemplate = {
		/* addr = */		(void *)0,
		/* coun = */		0,
		/* deal = */		FALSE,
		/* copy is meaningful only in overwrite mode */
		/* copy = */		MACH_MSG_PHYSICAL_COPY,
		/* disp = */		19,
		/* type = */		MACH_MSG_OOL_PORTS_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t intsTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	InP->msgh_body.msgh_descriptor_count = 2;
#if	UseStaticTemplates
	InP->ports = portsTemplate;
	InP->ports.address = (void *)(ports);
	InP->ports.count = portsCnt;
#else	/* UseStaticTemplates */
	InP->ports.address = (void *)(ports);
	InP->ports.count = portsCnt;
	InP->ports.disposition = 19;
	InP->ports.deallocate =  FALSE;
	InP->ports.type = MACH_MSG_OOL_PORTS_DESCRIPTOR;
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	InP->ints = intsTemplate;
	InP->ints.address = (void *)(ints);
	InP->ints.size = intsCnt * 4;
#else	/* UseStaticTemplates */
	InP->ints.address = (void *)(ints);
	InP->ints.size = intsCnt * 4;
	InP->ints.deallocate =  FALSE;
	InP->ints.copy = MACH_MSG_VIRTUAL_COPY;
	InP->ints.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */

	InP->NDR = NDR_record;

	InP->portsCnt = portsCnt;

	InP->intsCnt = intsCnt;

	InP->Head.msgh_reply_port = mig_get_reply_port();
	InP->Head.msgh_bits = MACH_MSGH_BITS_COMPLEX|
		MACH_MSGH_BITS(19, MACH_MSG_TYPE_MAKE_SEND_ONCE);
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = execserver;
	InP->Head.msgh_id = 26001;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendRpc(26001, "exec_setexecdata")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_RCV_MSG|MACH_MSG_OPTION_NONE, (mach_msg_size_t)sizeof(Request), (mach_msg_size_t)sizeof(Reply), InP->Head.msgh_reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendRpc(26001, "exec_setexecdata")
	if (msg_result != MACH_MSG_SUCCESS) {
		__MachMsgErrorWithoutTimeout(msg_result);
	}
	if (msg_result != MACH_MSG_SUCCESS) {
		{ return msg_result; }
	}


#if	defined(__MIG_check__Reply__exec_setexecdata_t__defined)
	check_result = __MIG_check__Reply__exec_setexecdata_t((__Reply__exec_setexecdata_t *)Out0P);
	if (check_result != MACH_MSG_SUCCESS) {
		mach_msg_destroy(&Out0P->Head);
		{ return check_result; }
	}
#endif	/* defined(__MIG_check__Reply__exec_setexecdata_t__defined) */

	return KERN_SUCCESS;
}

#if ( __MigTypeCheck )
#if __MIG_check__Reply__exec_subsystem__
#if !defined(__MIG_check__Reply__exec_exec_file_t__defined)
#define __MIG_check__Reply__exec_exec_file_t__defined

mig_internal kern_return_t __MIG_check__Reply__exec_exec_file_t(__Reply__exec_exec_file_t *Out0P)
{

	typedef __Reply__exec_exec_file_t __Reply __attribute__((unused));
	if (Out0P->Head.msgh_id != 26102) {
	    if (Out0P->Head.msgh_id == MACH_NOTIFY_SEND_ONCE)
		{ return MIG_SERVER_DIED; }
	    else
		{ return MIG_REPLY_MISMATCH; }
	}

#if	__MigTypeCheck
	if ((Out0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (Out0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Reply)))
		{ return MIG_TYPE_ERROR ; }
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (Out0P->Head.msgh_request_port != MACH_PORT_NULL) {
		return MIG_TYPE_ERROR;
	}
#endif	/* __MigTypeCheck */
	{
		return Out0P->RetCode;
	}
}
#endif /* !defined(__MIG_check__Reply__exec_exec_file_t__defined) */
#endif /* __MIG_check__Reply__exec_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine exec_exec_file */
mig_external kern_return_t exec_exec_file
(
	exec_t execserver,
	file_t file,
	mach_port_t task,
	int flags,
	data_t filename,
	mach_msg_type_number_t filenameCnt
)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t file;
		mach_msg_port_descriptor_t task;
		mach_msg_ool_descriptor_t filename;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int flags;
		mach_msg_type_number_t filenameCnt;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
		mach_msg_trailer_t trailer;
	} Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		kern_return_t RetCode;
	} __Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
		Reply Out;
	} Mess;

	Request *InP = &Mess.In;
	Reply *Out0P = &Mess.Out;

	mach_msg_return_t msg_result;

#ifdef	__MIG_check__Reply__exec_exec_file_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__exec_exec_file_t__defined */

	__DeclareSendRpc(26002, "exec_exec_file")

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t fileTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t taskTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t filenameTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	InP->msgh_body.msgh_descriptor_count = 3;
#if	UseStaticTemplates
	InP->file = fileTemplate;
	InP->file.name = file;
#else	/* UseStaticTemplates */
	InP->file.name = file;
	InP->file.disposition = 19;
	InP->file.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	InP->task = taskTemplate;
	InP->task.name = task;
#else	/* UseStaticTemplates */
	InP->task.name = task;
	InP->task.disposition = 19;
	InP->task.type = MACH_MSG_PORT_DESCRIPTOR;
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	InP->filename = filenameTemplate;
	InP->filename.address = (void *)(filename);
	InP->filename.size = filenameCnt;
#else	/* UseStaticTemplates */
	InP->filename.address = (void *)(filename);
	InP->filename.size = filenameCnt;
	InP->filename.deallocate =  FALSE;
	InP->filename.copy = MACH_MSG_VIRTUAL_COPY;
	InP->filename.type = MACH_MSG_OOL_DESCRIPTOR;
#endif	/* UseStaticTemplates */

	InP->NDR = NDR_record;

	InP->flags = flags;

	InP->filenameCnt = filenameCnt;

	InP->Head.msgh_reply_port = mig_get_reply_port();
	InP->Head.msgh_bits = MACH_MSGH_BITS_COMPLEX|
		MACH_MSGH_BITS(19, MACH_MSG_TYPE_MAKE_SEND_ONCE);
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = execserver;
	InP->Head.msgh_id = 26002;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendRpc(26002, "exec_exec_file")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_RCV_MSG|MACH_MSG_OPTION_NONE, (mach_msg_size_t)sizeof(Request), (mach_msg_size_t)sizeof(Reply), InP->Head.msgh_reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendRpc(26002, "exec_exec_file")
	if (msg_result != MACH_MSG_SUCCESS) {
		__MachMsgErrorWithoutTimeout(msg_result);
	}
	if (msg_result != MACH_MSG_SUCCESS) {
		{ return msg_result; }
	}


#if	defined(__MIG_check__Reply__exec_exec_file_t__defined)
	check_result = __MIG_check__Reply__exec_exec_file_t((__Reply__exec_exec_file_t *)Out0P);
	if (check_result != MACH_MSG_SUCCESS) {
		mach_msg_destroy(&Out0P->Head);
		{ return check_result; }
	}
#endif	/* defined(__MIG_check__Reply__exec_exec_file_t__defined) */

	return KERN_SUCCESS;
}

#if ( __MigTypeCheck )
#if __MIG_check__Reply__exec_subsystem__
#if !defined(__MIG_check__Reply__exec_startup_get_info_t__defined)
#define __MIG_check__Reply__exec_startup_get_info_t__defined

mig_internal kern_return_t __MIG_check__Reply__exec_startup_get_info_t(__Reply__exec_startup_get_info_t *Out0P)
{

	typedef __Reply__exec_startup_get_info_t __Reply __attribute__((unused));
	boolean_t msgh_simple;
#if	__MigTypeCheck
	unsigned int msgh_size;
#endif	/* __MigTypeCheck */
	if (Out0P->Head.msgh_id != 26103) {
	    if (Out0P->Head.msgh_id == MACH_NOTIFY_SEND_ONCE)
		{ return MIG_SERVER_DIED; }
	    else
		{ return MIG_REPLY_MISMATCH; }
	}

	msgh_simple = !(Out0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX);
#if	__MigTypeCheck
	msgh_size = Out0P->Head.msgh_size;

	if ((msgh_simple || Out0P->msgh_body.msgh_descriptor_count != 5 ||
	    msgh_size != (mach_msg_size_t)sizeof(__Reply)) &&
	    (!msgh_simple || msgh_size != (mach_msg_size_t)sizeof(mig_reply_error_t) ||
	    ((mig_reply_error_t *)Out0P)->RetCode == KERN_SUCCESS))
		{ return MIG_TYPE_ERROR ; }
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (Out0P->Head.msgh_request_port != MACH_PORT_NULL) {
		return MIG_TYPE_ERROR;
	}
#endif	/* __MigTypeCheck */
	if (msgh_simple) {
		return ((mig_reply_error_t *)Out0P)->RetCode;
	}

#if	__MigTypeCheck
	if (Out0P->argv.type != MACH_MSG_OOL_DESCRIPTOR) {
		return MIG_TYPE_ERROR;
	}
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (Out0P->envp.type != MACH_MSG_OOL_DESCRIPTOR) {
		return MIG_TYPE_ERROR;
	}
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (Out0P->dtable.type != MACH_MSG_OOL_PORTS_DESCRIPTOR ||
	    Out0P->dtable.disposition != 17) {
		return MIG_TYPE_ERROR;
	}
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (Out0P->portarray.type != MACH_MSG_OOL_PORTS_DESCRIPTOR ||
	    Out0P->portarray.disposition != 17) {
		return MIG_TYPE_ERROR;
	}
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (Out0P->intarray.type != MACH_MSG_OOL_DESCRIPTOR) {
		return MIG_TYPE_ERROR;
	}
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (Out0P->argv.size != Out0P->argvCnt)
		return MIG_TYPE_ERROR;
	if (Out0P->envp.size != Out0P->envpCnt)
		return MIG_TYPE_ERROR;
	if (Out0P->dtable.count != Out0P->dtableCnt)
		return MIG_TYPE_ERROR;
	if (Out0P->portarray.count != Out0P->portarrayCnt)
		return MIG_TYPE_ERROR;
	if (Out0P->intarray.size / 4 != Out0P->intarrayCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Reply__exec_startup_get_info_t__defined) */
#endif /* __MIG_check__Reply__exec_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine exec_startup_get_info */
mig_external kern_return_t exec_startup_get_info
(
	mach_port_t bootstrap,
	int *user_entry,
	int *phdr_data,
	int *phdr_size,
	int *base_addr,
	int *stack_base,
	int *stack_size,
	int *flags,
	data_t *argv,
	mach_msg_type_number_t *argvCnt,
	data_t *envp,
	mach_msg_type_number_t *envpCnt,
	portarray_t *dtable,
	mach_msg_type_number_t *dtableCnt,
	portarray_t *portarray,
	mach_msg_type_number_t *portarrayCnt,
	intarray_t *intarray,
	mach_msg_type_number_t *intarrayCnt
)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t argv;
		mach_msg_ool_descriptor_t envp;
		mach_msg_ool_ports_descriptor_t dtable;
		mach_msg_ool_ports_descriptor_t portarray;
		mach_msg_ool_descriptor_t intarray;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int user_entry;
		int phdr_data;
		int phdr_size;
		int base_addr;
		int stack_base;
		int stack_size;
		int flags;
		mach_msg_type_number_t argvCnt;
		mach_msg_type_number_t envpCnt;
		mach_msg_type_number_t dtableCnt;
		mach_msg_type_number_t portarrayCnt;
		mach_msg_type_number_t intarrayCnt;
		mach_msg_trailer_t trailer;
	} Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t argv;
		mach_msg_ool_descriptor_t envp;
		mach_msg_ool_ports_descriptor_t dtable;
		mach_msg_ool_ports_descriptor_t portarray;
		mach_msg_ool_descriptor_t intarray;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int user_entry;
		int phdr_data;
		int phdr_size;
		int base_addr;
		int stack_base;
		int stack_size;
		int flags;
		mach_msg_type_number_t argvCnt;
		mach_msg_type_number_t envpCnt;
		mach_msg_type_number_t dtableCnt;
		mach_msg_type_number_t portarrayCnt;
		mach_msg_type_number_t intarrayCnt;
	} __Reply __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	union {
		Request In;
		Reply Out;
	} Mess;

	Request *InP = &Mess.In;
	Reply *Out0P = &Mess.Out;

	mach_msg_return_t msg_result;

#ifdef	__MIG_check__Reply__exec_startup_get_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Reply__exec_startup_get_info_t__defined */

	__DeclareSendRpc(26003, "exec_startup_get_info")

	InP->Head.msgh_reply_port = mig_get_reply_port();
	InP->Head.msgh_bits =
		MACH_MSGH_BITS(19, MACH_MSG_TYPE_MAKE_SEND_ONCE);
	/* msgh_size passed as argument */
	InP->Head.msgh_request_port = bootstrap;
	InP->Head.msgh_id = 26003;
	InP->Head.msgh_reserved = 0;
	
/* BEGIN VOUCHER CODE */

#ifdef USING_VOUCHERS
	if (voucher_mach_msg_set != NULL) {
		voucher_mach_msg_set(&InP->Head);
	}
#endif // USING_VOUCHERS
	
/* END VOUCHER CODE */

	__BeforeSendRpc(26003, "exec_startup_get_info")
	msg_result = mach_msg(&InP->Head, MACH_SEND_MSG|MACH_RCV_MSG|MACH_MSG_OPTION_NONE, (mach_msg_size_t)sizeof(Request), (mach_msg_size_t)sizeof(Reply), InP->Head.msgh_reply_port, MACH_MSG_TIMEOUT_NONE, MACH_PORT_NULL);
	__AfterSendRpc(26003, "exec_startup_get_info")
	if (msg_result != MACH_MSG_SUCCESS) {
		__MachMsgErrorWithoutTimeout(msg_result);
	}
	if (msg_result != MACH_MSG_SUCCESS) {
		{ return msg_result; }
	}


#if	defined(__MIG_check__Reply__exec_startup_get_info_t__defined)
	check_result = __MIG_check__Reply__exec_startup_get_info_t((__Reply__exec_startup_get_info_t *)Out0P);
	if (check_result != MACH_MSG_SUCCESS) {
		mach_msg_destroy(&Out0P->Head);
		{ return check_result; }
	}
#endif	/* defined(__MIG_check__Reply__exec_startup_get_info_t__defined) */

	*user_entry = Out0P->user_entry;

	*phdr_data = Out0P->phdr_data;

	*phdr_size = Out0P->phdr_size;

	*base_addr = Out0P->base_addr;

	*stack_base = Out0P->stack_base;

	*stack_size = Out0P->stack_size;

	*flags = Out0P->flags;

	*argv = (data_t)(Out0P->argv.address);
	*argvCnt = Out0P->argvCnt;

	*envp = (data_t)(Out0P->envp.address);
	*envpCnt = Out0P->envpCnt;

	*dtable = (portarray_t)(Out0P->dtable.address);
	*dtableCnt = Out0P->dtableCnt;

	*portarray = (portarray_t)(Out0P->portarray.address);
	*portarrayCnt = Out0P->portarrayCnt;

	*intarray = (intarray_t)(Out0P->intarray.address);
	*intarrayCnt = Out0P->intarrayCnt;

	return KERN_SUCCESS;
}
