#include "mach.h"
/*
 * IDENTIFICATION:
 * stub generated by bootstrap_cmds-138
 * OPTIONS: 
 */

/* Module exec */

#define	__MIG_check__Request__exec_subsystem__ 1

#include "execServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xexec_exec
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xexec_setexecdata
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xexec_exec_file
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xexec_startup_get_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__exec_subsystem__
#if !defined(__MIG_check__Request__exec_exec_t__defined)
#define __MIG_check__Request__exec_exec_t__defined

mig_internal kern_return_t __MIG_check__Request__exec_exec_t(__attribute__((__unused__)) __Request__exec_exec_t *In0P)
{

	typedef __Request__exec_exec_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 9) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->file.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->file.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->oldtask.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->oldtask.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->argv.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->envp.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->dtable.type != MACH_MSG_OOL_PORTS_DESCRIPTOR ||
	    In0P->dtable.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->portarray.type != MACH_MSG_OOL_PORTS_DESCRIPTOR ||
	    In0P->portarray.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->intarray.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->deallocnames.type != MACH_MSG_OOL_PORTS_DESCRIPTOR ||
	    In0P->deallocnames.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->destroynames.type != MACH_MSG_OOL_PORTS_DESCRIPTOR ||
	    In0P->destroynames.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->argv.size != In0P->argvCnt)
		return MIG_TYPE_ERROR;
	if (In0P->envp.size != In0P->envpCnt)
		return MIG_TYPE_ERROR;
	if (In0P->dtable.count != In0P->dtableCnt)
		return MIG_TYPE_ERROR;
	if (In0P->portarray.count != In0P->portarrayCnt)
		return MIG_TYPE_ERROR;
	if (In0P->intarray.size / 4 != In0P->intarrayCnt)
		return MIG_TYPE_ERROR;
	if (In0P->deallocnames.count != In0P->deallocnamesCnt)
		return MIG_TYPE_ERROR;
	if (In0P->destroynames.count != In0P->destroynamesCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__exec_exec_t__defined) */
#endif /* __MIG_check__Request__exec_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine exec_exec */
mig_internal novalue _Xexec_exec
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t file;
		mach_msg_port_descriptor_t oldtask;
		mach_msg_ool_descriptor_t argv;
		mach_msg_ool_descriptor_t envp;
		mach_msg_ool_ports_descriptor_t dtable;
		mach_msg_ool_ports_descriptor_t portarray;
		mach_msg_ool_descriptor_t intarray;
		mach_msg_ool_ports_descriptor_t deallocnames;
		mach_msg_ool_ports_descriptor_t destroynames;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int flags;
		mach_msg_type_number_t argvCnt;
		mach_msg_type_number_t envpCnt;
		mach_msg_type_number_t dtableCnt;
		mach_msg_type_number_t portarrayCnt;
		mach_msg_type_number_t intarrayCnt;
		mach_msg_type_number_t deallocnamesCnt;
		mach_msg_type_number_t destroynamesCnt;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__exec_exec_t Reply __attribute__((unused));
	typedef __Request__exec_exec_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__exec_exec_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__exec_exec_t__defined */

	__DeclareRcvRpc(26000, "exec_exec")
	__BeforeRcvRpc(26000, "exec_exec")

#if	defined(__MIG_check__Request__exec_exec_t__defined)
	check_result = __MIG_check__Request__exec_exec_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__exec_exec_t__defined) */

	OutP->RetCode = exec_exec(In0P->Head.msgh_request_port, In0P->file.name, In0P->oldtask.name, In0P->flags, (data_t)(In0P->argv.address), In0P->argv.size, (data_t)(In0P->envp.address), In0P->envp.size, (portarray_t)(In0P->dtable.address), In0P->dtable.count, (portarray_t)(In0P->portarray.address), In0P->portarray.count, (intarray_t)(In0P->intarray.address), In0P->intarray.size / 4, (portarray_t)(In0P->deallocnames.address), In0P->deallocnames.count, (portarray_t)(In0P->destroynames.address), In0P->destroynames.count);
	mig_deallocate((vm_offset_t) In0P->destroynames.address, 4 * In0P->destroynames.count);
	In0P->destroynames.address = (void *) 0;
	In0P->destroynames.count = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->deallocnames.address, 4 * In0P->deallocnames.count);
	In0P->deallocnames.address = (void *) 0;
	In0P->deallocnames.count = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->intarray.address, In0P->intarray.size);
	In0P->intarray.address = (void *) 0;
	In0P->intarray.size = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->portarray.address, 4 * In0P->portarray.count);
	In0P->portarray.address = (void *) 0;
	In0P->portarray.count = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->dtable.address, 4 * In0P->dtable.count);
	In0P->dtable.address = (void *) 0;
	In0P->dtable.count = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->envp.address, In0P->envp.size);
	In0P->envp.address = (void *) 0;
	In0P->envp.size = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->argv.address, In0P->argv.size);
	In0P->argv.address = (void *) 0;
	In0P->argv.size = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(26000, "exec_exec")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__exec_subsystem__
#if !defined(__MIG_check__Request__exec_setexecdata_t__defined)
#define __MIG_check__Request__exec_setexecdata_t__defined

mig_internal kern_return_t __MIG_check__Request__exec_setexecdata_t(__attribute__((__unused__)) __Request__exec_setexecdata_t *In0P)
{

	typedef __Request__exec_setexecdata_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 2) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->ports.type != MACH_MSG_OOL_PORTS_DESCRIPTOR ||
	    In0P->ports.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->ints.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->ports.count != In0P->portsCnt)
		return MIG_TYPE_ERROR;
	if (In0P->ints.size / 4 != In0P->intsCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__exec_setexecdata_t__defined) */
#endif /* __MIG_check__Request__exec_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine exec_setexecdata */
mig_internal novalue _Xexec_setexecdata
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_ports_descriptor_t ports;
		mach_msg_ool_descriptor_t ints;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t portsCnt;
		mach_msg_type_number_t intsCnt;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__exec_setexecdata_t Reply __attribute__((unused));
	typedef __Request__exec_setexecdata_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__exec_setexecdata_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__exec_setexecdata_t__defined */

	__DeclareRcvRpc(26001, "exec_setexecdata")
	__BeforeRcvRpc(26001, "exec_setexecdata")

#if	defined(__MIG_check__Request__exec_setexecdata_t__defined)
	check_result = __MIG_check__Request__exec_setexecdata_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__exec_setexecdata_t__defined) */

	OutP->RetCode = exec_setexecdata(In0P->Head.msgh_request_port, (portarray_t)(In0P->ports.address), In0P->ports.count, (intarray_t)(In0P->ints.address), In0P->ints.size / 4);
	mig_deallocate((vm_offset_t) In0P->ints.address, In0P->ints.size);
	In0P->ints.address = (void *) 0;
	In0P->ints.size = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->ports.address, 4 * In0P->ports.count);
	In0P->ports.address = (void *) 0;
	In0P->ports.count = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(26001, "exec_setexecdata")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__exec_subsystem__
#if !defined(__MIG_check__Request__exec_exec_file_t__defined)
#define __MIG_check__Request__exec_exec_file_t__defined

mig_internal kern_return_t __MIG_check__Request__exec_exec_file_t(__attribute__((__unused__)) __Request__exec_exec_file_t *In0P)
{

	typedef __Request__exec_exec_file_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 3) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->file.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->file.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->task.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->task.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->filename.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->filename.size != In0P->filenameCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__exec_exec_file_t__defined) */
#endif /* __MIG_check__Request__exec_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine exec_exec_file */
mig_internal novalue _Xexec_exec_file
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t file;
		mach_msg_port_descriptor_t task;
		mach_msg_ool_descriptor_t filename;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int flags;
		mach_msg_type_number_t filenameCnt;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__exec_exec_file_t Reply __attribute__((unused));
	typedef __Request__exec_exec_file_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__exec_exec_file_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__exec_exec_file_t__defined */

	__DeclareRcvRpc(26002, "exec_exec_file")
	__BeforeRcvRpc(26002, "exec_exec_file")

#if	defined(__MIG_check__Request__exec_exec_file_t__defined)
	check_result = __MIG_check__Request__exec_exec_file_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__exec_exec_file_t__defined) */

	OutP->RetCode = exec_exec_file(In0P->Head.msgh_request_port, In0P->file.name, In0P->task.name, In0P->flags, (data_t)(In0P->filename.address), In0P->filename.size);
	mig_deallocate((vm_offset_t) In0P->filename.address, In0P->filename.size);
	In0P->filename.address = (void *) 0;
	In0P->filename.size = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(26002, "exec_exec_file")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__exec_subsystem__
#if !defined(__MIG_check__Request__exec_startup_get_info_t__defined)
#define __MIG_check__Request__exec_startup_get_info_t__defined

mig_internal kern_return_t __MIG_check__Request__exec_startup_get_info_t(__attribute__((__unused__)) __Request__exec_startup_get_info_t *In0P)
{

	typedef __Request__exec_startup_get_info_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__exec_startup_get_info_t__defined) */
#endif /* __MIG_check__Request__exec_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine exec_startup_get_info */
mig_internal novalue _Xexec_startup_get_info
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__exec_startup_get_info_t Reply __attribute__((unused));
	typedef __Request__exec_startup_get_info_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__exec_startup_get_info_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__exec_startup_get_info_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t argvTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t envpTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_ports_descriptor_t dtableTemplate = {
		/* addr = */		(void *)0,
		/* coun = */		0,
		/* deal = */		FALSE,
		/* copy is meaningful only in overwrite mode */
		/* copy = */		MACH_MSG_PHYSICAL_COPY,
		/* disp = */		19,
		/* type = */		MACH_MSG_OOL_PORTS_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_ports_descriptor_t portarrayTemplate = {
		/* addr = */		(void *)0,
		/* coun = */		0,
		/* deal = */		FALSE,
		/* copy is meaningful only in overwrite mode */
		/* copy = */		MACH_MSG_PHYSICAL_COPY,
		/* disp = */		19,
		/* type = */		MACH_MSG_OOL_PORTS_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t intarrayTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(26003, "exec_startup_get_info")
	__BeforeRcvRpc(26003, "exec_startup_get_info")

#if	defined(__MIG_check__Request__exec_startup_get_info_t__defined)
	check_result = __MIG_check__Request__exec_startup_get_info_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__exec_startup_get_info_t__defined) */

#if	UseStaticTemplates
	OutP->argv = argvTemplate;
#else	/* UseStaticTemplates */
	OutP->argv.deallocate =  FALSE;
	OutP->argv.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->argv.pad1 = 0;
	OutP->argv.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->argv.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->envp = envpTemplate;
#else	/* UseStaticTemplates */
	OutP->envp.deallocate =  FALSE;
	OutP->envp.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->envp.pad1 = 0;
	OutP->envp.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->envp.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->dtable = dtableTemplate;
#else	/* UseStaticTemplates */
	OutP->dtable.disposition = 19;
	OutP->dtable.deallocate =  FALSE;
	OutP->dtable.type = MACH_MSG_OOL_PORTS_DESCRIPTOR;
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->portarray = portarrayTemplate;
#else	/* UseStaticTemplates */
	OutP->portarray.disposition = 19;
	OutP->portarray.deallocate =  FALSE;
	OutP->portarray.type = MACH_MSG_OOL_PORTS_DESCRIPTOR;
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->intarray = intarrayTemplate;
#else	/* UseStaticTemplates */
	OutP->intarray.deallocate =  FALSE;
	OutP->intarray.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->intarray.pad1 = 0;
	OutP->intarray.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->intarray.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->argvCnt = 0;

	OutP->envpCnt = 0;

	OutP->dtableCnt = 0;

	OutP->portarrayCnt = 0;

	OutP->intarrayCnt = 0;

	RetCode = exec_startup_get_info(In0P->Head.msgh_request_port, &OutP->user_entry, &OutP->phdr_data, &OutP->phdr_size, &OutP->base_addr, &OutP->stack_base, &OutP->stack_size, &OutP->flags, (data_t *)&(OutP->argv.address), &OutP->argvCnt, (data_t *)&(OutP->envp.address), &OutP->envpCnt, (portarray_t *)&(OutP->dtable.address), &OutP->dtableCnt, (portarray_t *)&(OutP->portarray.address), &OutP->portarrayCnt, (intarray_t *)&(OutP->intarray.address), &OutP->intarrayCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->argv.size = OutP->argvCnt;

	OutP->envp.size = OutP->envpCnt;

	OutP->dtable.count = OutP->dtableCnt;

	OutP->portarray.count = OutP->portarrayCnt;

	OutP->intarray.size = OutP->intarrayCnt * 4;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 5;
	__AfterRcvRpc(26003, "exec_startup_get_info")
}



/* Description of this subsystem, for use in direct RPC */
const struct exec_subsystem exec_subsystem = {
	exec_server_routine,
	26000,
	26004,
	(mach_msg_size_t)sizeof(union __ReplyUnion__exec_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xexec_exec, 18, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__exec_exec_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xexec_setexecdata, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__exec_setexecdata_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xexec_exec_file, 6, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__exec_exec_file_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xexec_startup_get_info, 18, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__exec_startup_get_info_t)},
	}
};

mig_external boolean_t exec_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 26003) || (InHeadP->msgh_id < 26000) ||
	    ((routine = exec_subsystem.routine[InHeadP->msgh_id - 26000].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t exec_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 26000;

	if ((msgh_id > 3) || (msgh_id < 0))
		return 0;

	return exec_subsystem.routine[msgh_id].stub_routine;
}
