#include "mach.h"
/*
 * IDENTIFICATION:
 * stub generated by bootstrap_cmds-138
 * OPTIONS: 
 */

/* Module fs */

#define	__MIG_check__Request__fs_subsystem__ 1

#include "filesystemServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xdir_lookup
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xdir_readdir
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xdir_mkdir
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xdir_rmdir
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xdir_unlink
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xdir_link
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xdir_rename
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xdir_mkfile
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfile_getstat
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfile_setstat
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfile_sync
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfile_set_size
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xio_read
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xio_write
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__dir_lookup_t__defined)
#define __MIG_check__Request__dir_lookup_t__defined

mig_internal kern_return_t __MIG_check__Request__dir_lookup_t(__attribute__((__unused__)) __Request__dir_lookup_t *In0P)
{

	typedef __Request__dir_lookup_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->name.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->name.size != In0P->nameCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__dir_lookup_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine dir_lookup */
mig_internal novalue _Xdir_lookup
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t name;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t nameCnt;
		int flags;
		mode_t mode;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__dir_lookup_t Reply __attribute__((unused));
	typedef __Request__dir_lookup_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__dir_lookup_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__dir_lookup_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t retry_nameTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t fileTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(22000, "dir_lookup")
	__BeforeRcvRpc(22000, "dir_lookup")

#if	defined(__MIG_check__Request__dir_lookup_t__defined)
	check_result = __MIG_check__Request__dir_lookup_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__dir_lookup_t__defined) */

#if	UseStaticTemplates
	OutP->retry_name = retry_nameTemplate;
#else	/* UseStaticTemplates */
	OutP->retry_name.deallocate =  FALSE;
	OutP->retry_name.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->retry_name.pad1 = 0;
	OutP->retry_name.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->retry_name.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->file = fileTemplate;
#else	/* UseStaticTemplates */
	OutP->file.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->file.pad1 = 0;
#endif
	OutP->file.pad2 = 0;
	OutP->file.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->file.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->retry_nameCnt = 0;

	RetCode = dir_lookup(In0P->Head.msgh_request_port, (data_t)(In0P->name.address), In0P->name.size, In0P->flags, In0P->mode, &OutP->do_retry, (data_t *)&(OutP->retry_name.address), &OutP->retry_nameCnt, &OutP->file.name);
	mig_deallocate((vm_offset_t) In0P->name.address, In0P->name.size);
	In0P->name.address = (void *) 0;
	In0P->name.size = (mach_msg_size_t) 0;
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->retry_name.size = OutP->retry_nameCnt;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 2;
	__AfterRcvRpc(22000, "dir_lookup")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__dir_readdir_t__defined)
#define __MIG_check__Request__dir_readdir_t__defined

mig_internal kern_return_t __MIG_check__Request__dir_readdir_t(__attribute__((__unused__)) __Request__dir_readdir_t *In0P)
{

	typedef __Request__dir_readdir_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__dir_readdir_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine dir_readdir */
mig_internal novalue _Xdir_readdir
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int entry;
		int nentries;
		int bufsiz;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__dir_readdir_t Reply __attribute__((unused));
	typedef __Request__dir_readdir_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__dir_readdir_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__dir_readdir_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t dataTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(22001, "dir_readdir")
	__BeforeRcvRpc(22001, "dir_readdir")

#if	defined(__MIG_check__Request__dir_readdir_t__defined)
	check_result = __MIG_check__Request__dir_readdir_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__dir_readdir_t__defined) */

#if	UseStaticTemplates
	OutP->data = dataTemplate;
#else	/* UseStaticTemplates */
	OutP->data.deallocate =  FALSE;
	OutP->data.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->data.pad1 = 0;
	OutP->data.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->data.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->dataCnt = 0;

	RetCode = dir_readdir(In0P->Head.msgh_request_port, (data_t *)&(OutP->data.address), &OutP->dataCnt, In0P->entry, In0P->nentries, In0P->bufsiz, &OutP->amount);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->data.size = OutP->dataCnt;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(22001, "dir_readdir")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__dir_mkdir_t__defined)
#define __MIG_check__Request__dir_mkdir_t__defined

mig_internal kern_return_t __MIG_check__Request__dir_mkdir_t(__attribute__((__unused__)) __Request__dir_mkdir_t *In0P)
{

	typedef __Request__dir_mkdir_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->name.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->name.size != In0P->nameCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__dir_mkdir_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine dir_mkdir */
mig_internal novalue _Xdir_mkdir
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t name;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t nameCnt;
		mode_t mode;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__dir_mkdir_t Reply __attribute__((unused));
	typedef __Request__dir_mkdir_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__dir_mkdir_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__dir_mkdir_t__defined */

	__DeclareRcvRpc(22002, "dir_mkdir")
	__BeforeRcvRpc(22002, "dir_mkdir")

#if	defined(__MIG_check__Request__dir_mkdir_t__defined)
	check_result = __MIG_check__Request__dir_mkdir_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__dir_mkdir_t__defined) */

	OutP->RetCode = dir_mkdir(In0P->Head.msgh_request_port, (data_t)(In0P->name.address), In0P->name.size, In0P->mode);
	mig_deallocate((vm_offset_t) In0P->name.address, In0P->name.size);
	In0P->name.address = (void *) 0;
	In0P->name.size = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22002, "dir_mkdir")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__dir_rmdir_t__defined)
#define __MIG_check__Request__dir_rmdir_t__defined

mig_internal kern_return_t __MIG_check__Request__dir_rmdir_t(__attribute__((__unused__)) __Request__dir_rmdir_t *In0P)
{

	typedef __Request__dir_rmdir_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->name.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->name.size != In0P->nameCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__dir_rmdir_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine dir_rmdir */
mig_internal novalue _Xdir_rmdir
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t name;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t nameCnt;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__dir_rmdir_t Reply __attribute__((unused));
	typedef __Request__dir_rmdir_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__dir_rmdir_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__dir_rmdir_t__defined */

	__DeclareRcvRpc(22003, "dir_rmdir")
	__BeforeRcvRpc(22003, "dir_rmdir")

#if	defined(__MIG_check__Request__dir_rmdir_t__defined)
	check_result = __MIG_check__Request__dir_rmdir_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__dir_rmdir_t__defined) */

	OutP->RetCode = dir_rmdir(In0P->Head.msgh_request_port, (data_t)(In0P->name.address), In0P->name.size);
	mig_deallocate((vm_offset_t) In0P->name.address, In0P->name.size);
	In0P->name.address = (void *) 0;
	In0P->name.size = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22003, "dir_rmdir")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__dir_unlink_t__defined)
#define __MIG_check__Request__dir_unlink_t__defined

mig_internal kern_return_t __MIG_check__Request__dir_unlink_t(__attribute__((__unused__)) __Request__dir_unlink_t *In0P)
{

	typedef __Request__dir_unlink_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->name.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->name.size != In0P->nameCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__dir_unlink_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine dir_unlink */
mig_internal novalue _Xdir_unlink
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t name;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t nameCnt;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__dir_unlink_t Reply __attribute__((unused));
	typedef __Request__dir_unlink_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__dir_unlink_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__dir_unlink_t__defined */

	__DeclareRcvRpc(22004, "dir_unlink")
	__BeforeRcvRpc(22004, "dir_unlink")

#if	defined(__MIG_check__Request__dir_unlink_t__defined)
	check_result = __MIG_check__Request__dir_unlink_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__dir_unlink_t__defined) */

	OutP->RetCode = dir_unlink(In0P->Head.msgh_request_port, (data_t)(In0P->name.address), In0P->name.size);
	mig_deallocate((vm_offset_t) In0P->name.address, In0P->name.size);
	In0P->name.address = (void *) 0;
	In0P->name.size = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22004, "dir_unlink")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__dir_link_t__defined)
#define __MIG_check__Request__dir_link_t__defined

mig_internal kern_return_t __MIG_check__Request__dir_link_t(__attribute__((__unused__)) __Request__dir_link_t *In0P)
{

	typedef __Request__dir_link_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 2) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->source.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->source.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->name.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->name.size != In0P->nameCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__dir_link_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine dir_link */
mig_internal novalue _Xdir_link
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t source;
		mach_msg_ool_descriptor_t name;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t nameCnt;
		int excl;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__dir_link_t Reply __attribute__((unused));
	typedef __Request__dir_link_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__dir_link_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__dir_link_t__defined */

	__DeclareRcvRpc(22005, "dir_link")
	__BeforeRcvRpc(22005, "dir_link")

#if	defined(__MIG_check__Request__dir_link_t__defined)
	check_result = __MIG_check__Request__dir_link_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__dir_link_t__defined) */

	OutP->RetCode = dir_link(In0P->Head.msgh_request_port, In0P->source.name, (data_t)(In0P->name.address), In0P->name.size, In0P->excl);
	mig_deallocate((vm_offset_t) In0P->name.address, In0P->name.size);
	In0P->name.address = (void *) 0;
	In0P->name.size = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22005, "dir_link")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__dir_rename_t__defined)
#define __MIG_check__Request__dir_rename_t__defined

mig_internal kern_return_t __MIG_check__Request__dir_rename_t(__attribute__((__unused__)) __Request__dir_rename_t *In0P)
{

	typedef __Request__dir_rename_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 3) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->oldname.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->newdir.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->newdir.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->newname.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->oldname.size != In0P->oldnameCnt)
		return MIG_TYPE_ERROR;
	if (In0P->newname.size != In0P->newnameCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__dir_rename_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine dir_rename */
mig_internal novalue _Xdir_rename
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t oldname;
		mach_msg_port_descriptor_t newdir;
		mach_msg_ool_descriptor_t newname;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t oldnameCnt;
		mach_msg_type_number_t newnameCnt;
		int excl;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__dir_rename_t Reply __attribute__((unused));
	typedef __Request__dir_rename_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__dir_rename_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__dir_rename_t__defined */

	__DeclareRcvRpc(22006, "dir_rename")
	__BeforeRcvRpc(22006, "dir_rename")

#if	defined(__MIG_check__Request__dir_rename_t__defined)
	check_result = __MIG_check__Request__dir_rename_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__dir_rename_t__defined) */

	OutP->RetCode = dir_rename(In0P->Head.msgh_request_port, (data_t)(In0P->oldname.address), In0P->oldname.size, In0P->newdir.name, (data_t)(In0P->newname.address), In0P->newname.size, In0P->excl);
	mig_deallocate((vm_offset_t) In0P->newname.address, In0P->newname.size);
	In0P->newname.address = (void *) 0;
	In0P->newname.size = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->oldname.address, In0P->oldname.size);
	In0P->oldname.address = (void *) 0;
	In0P->oldname.size = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22006, "dir_rename")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__dir_mkfile_t__defined)
#define __MIG_check__Request__dir_mkfile_t__defined

mig_internal kern_return_t __MIG_check__Request__dir_mkfile_t(__attribute__((__unused__)) __Request__dir_mkfile_t *In0P)
{

	typedef __Request__dir_mkfile_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__dir_mkfile_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine dir_mkfile */
mig_internal novalue _Xdir_mkfile
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int flags;
		mode_t mode;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__dir_mkfile_t Reply __attribute__((unused));
	typedef __Request__dir_mkfile_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__dir_mkfile_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__dir_mkfile_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t fileTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(22007, "dir_mkfile")
	__BeforeRcvRpc(22007, "dir_mkfile")

#if	defined(__MIG_check__Request__dir_mkfile_t__defined)
	check_result = __MIG_check__Request__dir_mkfile_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__dir_mkfile_t__defined) */

#if	UseStaticTemplates
	OutP->file = fileTemplate;
#else	/* UseStaticTemplates */
	OutP->file.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->file.pad1 = 0;
#endif
	OutP->file.pad2 = 0;
	OutP->file.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->file.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = dir_mkfile(In0P->Head.msgh_request_port, In0P->flags, In0P->mode, &OutP->file.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(22007, "dir_mkfile")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__file_getstat_t__defined)
#define __MIG_check__Request__file_getstat_t__defined

mig_internal kern_return_t __MIG_check__Request__file_getstat_t(__attribute__((__unused__)) __Request__file_getstat_t *In0P)
{

	typedef __Request__file_getstat_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__file_getstat_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine file_getstat */
mig_internal novalue _Xfile_getstat
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__file_getstat_t Reply __attribute__((unused));
	typedef __Request__file_getstat_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__file_getstat_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__file_getstat_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t stat_dataTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(22008, "file_getstat")
	__BeforeRcvRpc(22008, "file_getstat")

#if	defined(__MIG_check__Request__file_getstat_t__defined)
	check_result = __MIG_check__Request__file_getstat_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__file_getstat_t__defined) */

#if	UseStaticTemplates
	OutP->stat_data = stat_dataTemplate;
#else	/* UseStaticTemplates */
	OutP->stat_data.deallocate =  FALSE;
	OutP->stat_data.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->stat_data.pad1 = 0;
	OutP->stat_data.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->stat_data.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->stat_dataCnt = 0;

	RetCode = file_getstat(In0P->Head.msgh_request_port, (data_t *)&(OutP->stat_data.address), &OutP->stat_dataCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->stat_data.size = OutP->stat_dataCnt;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(22008, "file_getstat")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__file_setstat_t__defined)
#define __MIG_check__Request__file_setstat_t__defined

mig_internal kern_return_t __MIG_check__Request__file_setstat_t(__attribute__((__unused__)) __Request__file_setstat_t *In0P)
{

	typedef __Request__file_setstat_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->stat_data.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->stat_data.size != In0P->stat_dataCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__file_setstat_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine file_setstat */
mig_internal novalue _Xfile_setstat
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t stat_data;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t stat_dataCnt;
		int stat_flags;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__file_setstat_t Reply __attribute__((unused));
	typedef __Request__file_setstat_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__file_setstat_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__file_setstat_t__defined */

	__DeclareRcvRpc(22009, "file_setstat")
	__BeforeRcvRpc(22009, "file_setstat")

#if	defined(__MIG_check__Request__file_setstat_t__defined)
	check_result = __MIG_check__Request__file_setstat_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__file_setstat_t__defined) */

	OutP->RetCode = file_setstat(In0P->Head.msgh_request_port, (data_t)(In0P->stat_data.address), In0P->stat_data.size, In0P->stat_flags);
	mig_deallocate((vm_offset_t) In0P->stat_data.address, In0P->stat_data.size);
	In0P->stat_data.address = (void *) 0;
	In0P->stat_data.size = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22009, "file_setstat")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__file_sync_t__defined)
#define __MIG_check__Request__file_sync_t__defined

mig_internal kern_return_t __MIG_check__Request__file_sync_t(__attribute__((__unused__)) __Request__file_sync_t *In0P)
{

	typedef __Request__file_sync_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__file_sync_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine file_sync */
mig_internal novalue _Xfile_sync
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int wait;
		int omit_metadata;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__file_sync_t Reply __attribute__((unused));
	typedef __Request__file_sync_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__file_sync_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__file_sync_t__defined */

	__DeclareRcvRpc(22010, "file_sync")
	__BeforeRcvRpc(22010, "file_sync")

#if	defined(__MIG_check__Request__file_sync_t__defined)
	check_result = __MIG_check__Request__file_sync_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__file_sync_t__defined) */

	OutP->RetCode = file_sync(In0P->Head.msgh_request_port, In0P->wait, In0P->omit_metadata);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22010, "file_sync")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__file_set_size_t__defined)
#define __MIG_check__Request__file_set_size_t__defined

mig_internal kern_return_t __MIG_check__Request__file_set_size_t(__attribute__((__unused__)) __Request__file_set_size_t *In0P)
{

	typedef __Request__file_set_size_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__file_set_size_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine file_set_size */
mig_internal novalue _Xfile_set_size
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		off_t size;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__file_set_size_t Reply __attribute__((unused));
	typedef __Request__file_set_size_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__file_set_size_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__file_set_size_t__defined */

	__DeclareRcvRpc(22011, "file_set_size")
	__BeforeRcvRpc(22011, "file_set_size")

#if	defined(__MIG_check__Request__file_set_size_t__defined)
	check_result = __MIG_check__Request__file_set_size_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__file_set_size_t__defined) */

	OutP->RetCode = file_set_size(In0P->Head.msgh_request_port, In0P->size);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22011, "file_set_size")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__io_read_t__defined)
#define __MIG_check__Request__io_read_t__defined

mig_internal kern_return_t __MIG_check__Request__io_read_t(__attribute__((__unused__)) __Request__io_read_t *In0P)
{

	typedef __Request__io_read_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__io_read_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine io_read */
mig_internal novalue _Xio_read
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		off_t offset;
		int amount;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__io_read_t Reply __attribute__((unused));
	typedef __Request__io_read_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__io_read_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__io_read_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t dataTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(22015, "io_read")
	__BeforeRcvRpc(22015, "io_read")

#if	defined(__MIG_check__Request__io_read_t__defined)
	check_result = __MIG_check__Request__io_read_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__io_read_t__defined) */

#if	UseStaticTemplates
	OutP->data = dataTemplate;
#else	/* UseStaticTemplates */
	OutP->data.deallocate =  FALSE;
	OutP->data.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->data.pad1 = 0;
	OutP->data.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->data.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->dataCnt = 0;

	RetCode = io_read(In0P->Head.msgh_request_port, (data_t *)&(OutP->data.address), &OutP->dataCnt, In0P->offset, In0P->amount);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->data.size = OutP->dataCnt;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(22015, "io_read")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__io_write_t__defined)
#define __MIG_check__Request__io_write_t__defined

mig_internal kern_return_t __MIG_check__Request__io_write_t(__attribute__((__unused__)) __Request__io_write_t *In0P)
{

	typedef __Request__io_write_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->data.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->data.size != In0P->dataCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__io_write_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine io_write */
mig_internal novalue _Xio_write
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t data;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t dataCnt;
		off_t offset;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__io_write_t Reply __attribute__((unused));
	typedef __Request__io_write_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__io_write_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__io_write_t__defined */

	__DeclareRcvRpc(22016, "io_write")
	__BeforeRcvRpc(22016, "io_write")

#if	defined(__MIG_check__Request__io_write_t__defined)
	check_result = __MIG_check__Request__io_write_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__io_write_t__defined) */

	OutP->RetCode = io_write(In0P->Head.msgh_request_port, (data_t)(In0P->data.address), In0P->data.size, In0P->offset, &OutP->amount);
	mig_deallocate((vm_offset_t) In0P->data.address, In0P->data.size);
	In0P->data.address = (void *) 0;
	In0P->data.size = (mach_msg_size_t) 0;
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(22016, "io_write")
}



/* Description of this subsystem, for use in direct RPC */
const struct fs_subsystem fs_subsystem = {
	fs_server_routine,
	22000,
	22017,
	(mach_msg_size_t)sizeof(union __ReplyUnion__fs_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xdir_lookup, 9, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__dir_lookup_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xdir_readdir, 7, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__dir_readdir_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xdir_mkdir, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__dir_mkdir_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xdir_rmdir, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__dir_rmdir_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xdir_unlink, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__dir_unlink_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xdir_link, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__dir_link_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xdir_rename, 7, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__dir_rename_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xdir_mkfile, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__dir_mkfile_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfile_getstat, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__file_getstat_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfile_setstat, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__file_setstat_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfile_sync, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__file_sync_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfile_set_size, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__file_set_size_t)},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xio_read, 6, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__io_read_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xio_write, 6, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__io_write_t)},
	}
};

mig_external boolean_t fs_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 22016) || (InHeadP->msgh_id < 22000) ||
	    ((routine = fs_subsystem.routine[InHeadP->msgh_id - 22000].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t fs_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 22000;

	if ((msgh_id > 16) || (msgh_id < 0))
		return 0;

	return fs_subsystem.routine[msgh_id].stub_routine;
}
