/*
 * IDENTIFICATION:
 * stub generated by bootstrap_cmds-138
 * OPTIONS: 
 */

/* Module fs */

#define	__MIG_check__Request__fs_subsystem__ 1

#include "fsServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xfile_check_access
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfile_statfs
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfile_sync
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfile_chmod
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfile_get_translator
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__file_check_access_t__defined)
#define __MIG_check__Request__file_check_access_t__defined

mig_internal kern_return_t __MIG_check__Request__file_check_access_t(__attribute__((__unused__)) __Request__file_check_access_t *In0P)
{

	typedef __Request__file_check_access_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__file_check_access_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine file_check_access */
mig_internal novalue _Xfile_check_access
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__file_check_access_t Reply __attribute__((unused));
	typedef __Request__file_check_access_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__file_check_access_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__file_check_access_t__defined */

	__DeclareRcvRpc(20000, "file_check_access")
	__BeforeRcvRpc(20000, "file_check_access")

#if	defined(__MIG_check__Request__file_check_access_t__defined)
	check_result = __MIG_check__Request__file_check_access_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__file_check_access_t__defined) */

	OutP->RetCode = file_check_access(In0P->Head.msgh_request_port, &OutP->allowed);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(20000, "file_check_access")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__file_statfs_t__defined)
#define __MIG_check__Request__file_statfs_t__defined

mig_internal kern_return_t __MIG_check__Request__file_statfs_t(__attribute__((__unused__)) __Request__file_statfs_t *In0P)
{

	typedef __Request__file_statfs_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__file_statfs_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine file_statfs */
mig_internal novalue _Xfile_statfs
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__file_statfs_t Reply __attribute__((unused));
	typedef __Request__file_statfs_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__file_statfs_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__file_statfs_t__defined */

	__DeclareRcvRpc(20001, "file_statfs")
	__BeforeRcvRpc(20001, "file_statfs")

#if	defined(__MIG_check__Request__file_statfs_t__defined)
	check_result = __MIG_check__Request__file_statfs_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__file_statfs_t__defined) */

	OutP->RetCode = file_statfs(In0P->Head.msgh_request_port, &OutP->info);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(20001, "file_statfs")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__file_sync_t__defined)
#define __MIG_check__Request__file_sync_t__defined

mig_internal kern_return_t __MIG_check__Request__file_sync_t(__attribute__((__unused__)) __Request__file_sync_t *In0P)
{

	typedef __Request__file_sync_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__file_sync_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine file_sync */
mig_internal novalue _Xfile_sync
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int wait;
		int omit_metadata;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__file_sync_t Reply __attribute__((unused));
	typedef __Request__file_sync_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__file_sync_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__file_sync_t__defined */

	__DeclareRcvRpc(20002, "file_sync")
	__BeforeRcvRpc(20002, "file_sync")

#if	defined(__MIG_check__Request__file_sync_t__defined)
	check_result = __MIG_check__Request__file_sync_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__file_sync_t__defined) */

	OutP->RetCode = file_sync(In0P->Head.msgh_request_port, In0P->wait, In0P->omit_metadata);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(20002, "file_sync")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__file_chmod_t__defined)
#define __MIG_check__Request__file_chmod_t__defined

mig_internal kern_return_t __MIG_check__Request__file_chmod_t(__attribute__((__unused__)) __Request__file_chmod_t *In0P)
{

	typedef __Request__file_chmod_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__file_chmod_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine file_chmod */
mig_internal novalue _Xfile_chmod
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		mode_t new_mode;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__file_chmod_t Reply __attribute__((unused));
	typedef __Request__file_chmod_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__file_chmod_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__file_chmod_t__defined */

	__DeclareRcvRpc(20003, "file_chmod")
	__BeforeRcvRpc(20003, "file_chmod")

#if	defined(__MIG_check__Request__file_chmod_t__defined)
	check_result = __MIG_check__Request__file_chmod_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__file_chmod_t__defined) */

	OutP->RetCode = file_chmod(In0P->Head.msgh_request_port, In0P->new_mode);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(20003, "file_chmod")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fs_subsystem__
#if !defined(__MIG_check__Request__file_get_translator_t__defined)
#define __MIG_check__Request__file_get_translator_t__defined

mig_internal kern_return_t __MIG_check__Request__file_get_translator_t(__attribute__((__unused__)) __Request__file_get_translator_t *In0P)
{

	typedef __Request__file_get_translator_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__file_get_translator_t__defined) */
#endif /* __MIG_check__Request__fs_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine file_get_translator */
mig_internal novalue _Xfile_get_translator
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__file_get_translator_t Reply __attribute__((unused));
	typedef __Request__file_get_translator_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__file_get_translator_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__file_get_translator_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t translatorTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		TRUE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(20004, "file_get_translator")
	__BeforeRcvRpc(20004, "file_get_translator")

#if	defined(__MIG_check__Request__file_get_translator_t__defined)
	check_result = __MIG_check__Request__file_get_translator_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__file_get_translator_t__defined) */

#if	UseStaticTemplates
	OutP->translator = translatorTemplate;
#else	/* UseStaticTemplates */
	OutP->translator.deallocate =  TRUE;
	OutP->translator.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->translator.pad1 = 0;
	OutP->translator.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->translator.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->translatorCnt = 0;

	RetCode = file_get_translator(In0P->Head.msgh_request_port, (data_t *)&(OutP->translator.address), &OutP->translatorCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->translator.size = OutP->translatorCnt;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(20004, "file_get_translator")
}



/* Description of this subsystem, for use in direct RPC */
const struct fs_subsystem fs_subsystem = {
	fs_server_routine,
	20000,
	20005,
	(mach_msg_size_t)sizeof(union __ReplyUnion__fs_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfile_check_access, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__file_check_access_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfile_statfs, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__file_statfs_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfile_sync, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__file_sync_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfile_chmod, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__file_chmod_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfile_get_translator, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__file_get_translator_t)},
	}
};

mig_external boolean_t fs_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 20004) || (InHeadP->msgh_id < 20000) ||
	    ((routine = fs_subsystem.routine[InHeadP->msgh_id - 20000].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t fs_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 20000;

	if ((msgh_id > 4) || (msgh_id < 0))
		return 0;

	return fs_subsystem.routine[msgh_id].stub_routine;
}
