/*
 * IDENTIFICATION:
 * stub generated by bootstrap_cmds-138
 * OPTIONS: 
 */

/* Module fsys */

#define	__MIG_check__Request__fsys_subsystem__ 1

#include "fsysServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xfsys_getroot
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfsys_goaway
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xfsys_syncfs
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__fsys_subsystem__
#if !defined(__MIG_check__Request__fsys_getroot_t__defined)
#define __MIG_check__Request__fsys_getroot_t__defined

mig_internal kern_return_t __MIG_check__Request__fsys_getroot_t(__attribute__((__unused__)) __Request__fsys_getroot_t *In0P)
{

	typedef __Request__fsys_getroot_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 3) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->dotdot.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->dotdot.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->gen_uids.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->gen_gids.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->gen_uids.size / 4 != In0P->gen_uidsCnt)
		return MIG_TYPE_ERROR;
	if (In0P->gen_gids.size / 4 != In0P->gen_gidsCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__fsys_getroot_t__defined) */
#endif /* __MIG_check__Request__fsys_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine fsys_getroot */
mig_internal novalue _Xfsys_getroot
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t dotdot;
		mach_msg_ool_descriptor_t gen_uids;
		mach_msg_ool_descriptor_t gen_gids;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t gen_uidsCnt;
		mach_msg_type_number_t gen_gidsCnt;
		int flags;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__fsys_getroot_t Reply __attribute__((unused));
	typedef __Request__fsys_getroot_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__fsys_getroot_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__fsys_getroot_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t resultTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		((mach_msg_type_name_t) -1),
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	mach_msg_type_name_t resultPoly;

	__DeclareRcvRpc(22000, "fsys_getroot")
	__BeforeRcvRpc(22000, "fsys_getroot")

#if	defined(__MIG_check__Request__fsys_getroot_t__defined)
	check_result = __MIG_check__Request__fsys_getroot_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__fsys_getroot_t__defined) */

#if	UseStaticTemplates
	OutP->result = resultTemplate;
#else	/* UseStaticTemplates */
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->result.pad1 = 0;
#endif
	OutP->result.pad2 = 0;
	OutP->result.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->result.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = fsys_getroot(In0P->Head.msgh_request_port, In0P->dotdot.name, (idarray_t)(In0P->gen_uids.address), In0P->gen_uids.size / 4, (idarray_t)(In0P->gen_gids.address), In0P->gen_gids.size / 4, In0P->flags, &OutP->do_retry, OutP->retry_name, &OutP->result.name, &resultPoly);
	mig_deallocate((vm_offset_t) In0P->gen_gids.address, In0P->gen_gids.size);
	In0P->gen_gids.address = (void *) 0;
	In0P->gen_gids.size = (mach_msg_size_t) 0;
	mig_deallocate((vm_offset_t) In0P->gen_uids.address, In0P->gen_uids.size);
	In0P->gen_uids.address = (void *) 0;
	In0P->gen_uids.size = (mach_msg_size_t) 0;
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->result.disposition = resultPoly;

	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(22000, "fsys_getroot")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fsys_subsystem__
#if !defined(__MIG_check__Request__fsys_goaway_t__defined)
#define __MIG_check__Request__fsys_goaway_t__defined

mig_internal kern_return_t __MIG_check__Request__fsys_goaway_t(__attribute__((__unused__)) __Request__fsys_goaway_t *In0P)
{

	typedef __Request__fsys_goaway_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__fsys_goaway_t__defined) */
#endif /* __MIG_check__Request__fsys_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine fsys_goaway */
mig_internal novalue _Xfsys_goaway
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int flags;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__fsys_goaway_t Reply __attribute__((unused));
	typedef __Request__fsys_goaway_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__fsys_goaway_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__fsys_goaway_t__defined */

	__DeclareRcvRpc(22001, "fsys_goaway")
	__BeforeRcvRpc(22001, "fsys_goaway")

#if	defined(__MIG_check__Request__fsys_goaway_t__defined)
	check_result = __MIG_check__Request__fsys_goaway_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__fsys_goaway_t__defined) */

	OutP->RetCode = fsys_goaway(In0P->Head.msgh_request_port, In0P->flags);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22001, "fsys_goaway")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__fsys_subsystem__
#if !defined(__MIG_check__Request__fsys_syncfs_t__defined)
#define __MIG_check__Request__fsys_syncfs_t__defined

mig_internal kern_return_t __MIG_check__Request__fsys_syncfs_t(__attribute__((__unused__)) __Request__fsys_syncfs_t *In0P)
{

	typedef __Request__fsys_syncfs_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__fsys_syncfs_t__defined) */
#endif /* __MIG_check__Request__fsys_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine fsys_syncfs */
mig_internal novalue _Xfsys_syncfs
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int wait;
		int do_children;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__fsys_syncfs_t Reply __attribute__((unused));
	typedef __Request__fsys_syncfs_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__fsys_syncfs_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__fsys_syncfs_t__defined */

	__DeclareRcvRpc(22002, "fsys_syncfs")
	__BeforeRcvRpc(22002, "fsys_syncfs")

#if	defined(__MIG_check__Request__fsys_syncfs_t__defined)
	check_result = __MIG_check__Request__fsys_syncfs_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__fsys_syncfs_t__defined) */

	OutP->RetCode = fsys_syncfs(In0P->Head.msgh_request_port, In0P->wait, In0P->do_children);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(22002, "fsys_syncfs")
}



/* Description of this subsystem, for use in direct RPC */
const struct fsys_subsystem fsys_subsystem = {
	fsys_server_routine,
	22000,
	22003,
	(mach_msg_size_t)sizeof(union __ReplyUnion__fsys_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfsys_getroot, 11, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__fsys_getroot_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfsys_goaway, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__fsys_goaway_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xfsys_syncfs, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__fsys_syncfs_t)},
	}
};

mig_external boolean_t fsys_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 22002) || (InHeadP->msgh_id < 22000) ||
	    ((routine = fsys_subsystem.routine[InHeadP->msgh_id - 22000].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t fsys_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 22000;

	if ((msgh_id > 2) || (msgh_id < 0))
		return 0;

	return fsys_subsystem.routine[msgh_id].stub_routine;
}
