#include "mach.h"
/*
 * IDENTIFICATION:
 * stub generated by bootstrap_cmds-138
 * OPTIONS: 
 */

/* Module process */

#define	__MIG_check__Request__process_subsystem__ 1

#include "processServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xproc_getprivports
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xproc_getallpids
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xproc_getpids
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xproc_wait
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xproc_pid2task
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xproc_task2pid
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__process_subsystem__
#if !defined(__MIG_check__Request__proc_getprivports_t__defined)
#define __MIG_check__Request__proc_getprivports_t__defined

mig_internal kern_return_t __MIG_check__Request__proc_getprivports_t(__attribute__((__unused__)) __Request__proc_getprivports_t *In0P)
{

	typedef __Request__proc_getprivports_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__proc_getprivports_t__defined) */
#endif /* __MIG_check__Request__process_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine proc_getprivports */
mig_internal novalue _Xproc_getprivports
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__proc_getprivports_t Reply __attribute__((unused));
	typedef __Request__proc_getprivports_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__proc_getprivports_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__proc_getprivports_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t host_privTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t device_masterTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(24004, "proc_getprivports")
	__BeforeRcvRpc(24004, "proc_getprivports")

#if	defined(__MIG_check__Request__proc_getprivports_t__defined)
	check_result = __MIG_check__Request__proc_getprivports_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__proc_getprivports_t__defined) */

#if	UseStaticTemplates
	OutP->host_priv = host_privTemplate;
#else	/* UseStaticTemplates */
	OutP->host_priv.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->host_priv.pad1 = 0;
#endif
	OutP->host_priv.pad2 = 0;
	OutP->host_priv.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->host_priv.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


#if	UseStaticTemplates
	OutP->device_master = device_masterTemplate;
#else	/* UseStaticTemplates */
	OutP->device_master.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->device_master.pad1 = 0;
#endif
	OutP->device_master.pad2 = 0;
	OutP->device_master.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->device_master.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = proc_getprivports(In0P->Head.msgh_request_port, &OutP->host_priv.name, &OutP->device_master.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 2;
	__AfterRcvRpc(24004, "proc_getprivports")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__process_subsystem__
#if !defined(__MIG_check__Request__proc_getallpids_t__defined)
#define __MIG_check__Request__proc_getallpids_t__defined

mig_internal kern_return_t __MIG_check__Request__proc_getallpids_t(__attribute__((__unused__)) __Request__proc_getallpids_t *In0P)
{

	typedef __Request__proc_getallpids_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__proc_getallpids_t__defined) */
#endif /* __MIG_check__Request__process_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine proc_getallpids */
mig_internal novalue _Xproc_getallpids
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__proc_getallpids_t Reply __attribute__((unused));
	typedef __Request__proc_getallpids_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__proc_getallpids_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__proc_getallpids_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t pidarrayTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(24005, "proc_getallpids")
	__BeforeRcvRpc(24005, "proc_getallpids")

#if	defined(__MIG_check__Request__proc_getallpids_t__defined)
	check_result = __MIG_check__Request__proc_getallpids_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__proc_getallpids_t__defined) */

#if	UseStaticTemplates
	OutP->pidarray = pidarrayTemplate;
#else	/* UseStaticTemplates */
	OutP->pidarray.deallocate =  FALSE;
	OutP->pidarray.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->pidarray.pad1 = 0;
	OutP->pidarray.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->pidarray.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->pidarrayCnt = 0;

	RetCode = proc_getallpids(In0P->Head.msgh_request_port, (pidarray_t *)&(OutP->pidarray.address), &OutP->pidarrayCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->pidarray.size = OutP->pidarrayCnt * 4;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(24005, "proc_getallpids")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__process_subsystem__
#if !defined(__MIG_check__Request__proc_getpids_t__defined)
#define __MIG_check__Request__proc_getpids_t__defined

mig_internal kern_return_t __MIG_check__Request__proc_getpids_t(__attribute__((__unused__)) __Request__proc_getpids_t *In0P)
{

	typedef __Request__proc_getpids_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__proc_getpids_t__defined) */
#endif /* __MIG_check__Request__process_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine proc_getpids */
mig_internal novalue _Xproc_getpids
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__proc_getpids_t Reply __attribute__((unused));
	typedef __Request__proc_getpids_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__proc_getpids_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__proc_getpids_t__defined */

	__DeclareRcvRpc(24015, "proc_getpids")
	__BeforeRcvRpc(24015, "proc_getpids")

#if	defined(__MIG_check__Request__proc_getpids_t__defined)
	check_result = __MIG_check__Request__proc_getpids_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__proc_getpids_t__defined) */

	OutP->RetCode = proc_getpids(In0P->Head.msgh_request_port, &OutP->pid, &OutP->ppid, &OutP->orphaned);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(24015, "proc_getpids")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__process_subsystem__
#if !defined(__MIG_check__Request__proc_wait_t__defined)
#define __MIG_check__Request__proc_wait_t__defined

mig_internal kern_return_t __MIG_check__Request__proc_wait_t(__attribute__((__unused__)) __Request__proc_wait_t *In0P)
{

	typedef __Request__proc_wait_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__proc_wait_t__defined) */
#endif /* __MIG_check__Request__process_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine proc_wait */
mig_internal novalue _Xproc_wait
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		pid_t pid;
		int options;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__proc_wait_t Reply __attribute__((unused));
	typedef __Request__proc_wait_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__proc_wait_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__proc_wait_t__defined */

	__DeclareRcvRpc(24019, "proc_wait")
	__BeforeRcvRpc(24019, "proc_wait")

#if	defined(__MIG_check__Request__proc_wait_t__defined)
	check_result = __MIG_check__Request__proc_wait_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__proc_wait_t__defined) */

	OutP->RetCode = proc_wait(In0P->Head.msgh_request_port, In0P->pid, In0P->options, &OutP->status, &OutP->sigcode, &OutP->pid_status);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(24019, "proc_wait")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__process_subsystem__
#if !defined(__MIG_check__Request__proc_pid2task_t__defined)
#define __MIG_check__Request__proc_pid2task_t__defined

mig_internal kern_return_t __MIG_check__Request__proc_pid2task_t(__attribute__((__unused__)) __Request__proc_pid2task_t *In0P)
{

	typedef __Request__proc_pid2task_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__proc_pid2task_t__defined) */
#endif /* __MIG_check__Request__process_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine proc_pid2task */
mig_internal novalue _Xproc_pid2task
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		pid_t pid;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__proc_pid2task_t Reply __attribute__((unused));
	typedef __Request__proc_pid2task_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__proc_pid2task_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__proc_pid2task_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t taskTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(24028, "proc_pid2task")
	__BeforeRcvRpc(24028, "proc_pid2task")

#if	defined(__MIG_check__Request__proc_pid2task_t__defined)
	check_result = __MIG_check__Request__proc_pid2task_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__proc_pid2task_t__defined) */

#if	UseStaticTemplates
	OutP->task = taskTemplate;
#else	/* UseStaticTemplates */
	OutP->task.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->task.pad1 = 0;
#endif
	OutP->task.pad2 = 0;
	OutP->task.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->task.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = proc_pid2task(In0P->Head.msgh_request_port, In0P->pid, &OutP->task.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(24028, "proc_pid2task")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__process_subsystem__
#if !defined(__MIG_check__Request__proc_task2pid_t__defined)
#define __MIG_check__Request__proc_task2pid_t__defined

mig_internal kern_return_t __MIG_check__Request__proc_task2pid_t(__attribute__((__unused__)) __Request__proc_task2pid_t *In0P)
{

	typedef __Request__proc_task2pid_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->task.type != MACH_MSG_PORT_DESCRIPTOR ||
	    In0P->task.disposition != 17)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__proc_task2pid_t__defined) */
#endif /* __MIG_check__Request__process_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine proc_task2pid */
mig_internal novalue _Xproc_task2pid
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_port_descriptor_t task;
		/* end of the kernel processed data */
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__proc_task2pid_t Reply __attribute__((unused));
	typedef __Request__proc_task2pid_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__proc_task2pid_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__proc_task2pid_t__defined */

	__DeclareRcvRpc(24029, "proc_task2pid")
	__BeforeRcvRpc(24029, "proc_task2pid")

#if	defined(__MIG_check__Request__proc_task2pid_t__defined)
	check_result = __MIG_check__Request__proc_task2pid_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__proc_task2pid_t__defined) */

	OutP->RetCode = proc_task2pid(In0P->Head.msgh_request_port, In0P->task.name, &OutP->pid);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(24029, "proc_task2pid")
}



/* Description of this subsystem, for use in direct RPC */
const struct process_subsystem process_subsystem = {
	process_server_routine,
	24000,
	24030,
	(mach_msg_size_t)sizeof(union __ReplyUnion__process_subsystem),
	(vm_address_t)0,
	{
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xproc_getprivports, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__proc_getprivports_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xproc_getallpids, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__proc_getallpids_t)},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xproc_getpids, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__proc_getpids_t)},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xproc_wait, 6, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__proc_wait_t)},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
		{0, 0, 0, 0, 0, 0},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xproc_pid2task, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__proc_pid2task_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xproc_task2pid, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__proc_task2pid_t)},
	}
};

mig_external boolean_t process_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 24029) || (InHeadP->msgh_id < 24000) ||
	    ((routine = process_subsystem.routine[InHeadP->msgh_id - 24000].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t process_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 24000;

	if ((msgh_id > 29) || (msgh_id < 0))
		return 0;

	return process_subsystem.routine[msgh_id].stub_routine;
}
