#include "mach.h"
/*
 * IDENTIFICATION:
 * stub generated by bootstrap_cmds-138
 * OPTIONS: 
 */

/* Module socket */

#define	__MIG_check__Request__socket_subsystem__ 1

#include "socketServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xsocket_create
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_bind
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_listen
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_accept
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_connect
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_send
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_recv
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_name
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_peername
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_shutdown
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_getopt
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xsocket_setopt
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_create_t__defined)
#define __MIG_check__Request__socket_create_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_create_t(__attribute__((__unused__)) __Request__socket_create_t *In0P)
{

	typedef __Request__socket_create_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_create_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_create */
mig_internal novalue _Xsocket_create
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int sock_type;
		int protocol;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_create_t Reply __attribute__((unused));
	typedef __Request__socket_create_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_create_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_create_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t sockTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(26100, "socket_create")
	__BeforeRcvRpc(26100, "socket_create")

#if	defined(__MIG_check__Request__socket_create_t__defined)
	check_result = __MIG_check__Request__socket_create_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_create_t__defined) */

#if	UseStaticTemplates
	OutP->sock = sockTemplate;
#else	/* UseStaticTemplates */
	OutP->sock.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->sock.pad1 = 0;
#endif
	OutP->sock.pad2 = 0;
	OutP->sock.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->sock.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = socket_create(In0P->Head.msgh_request_port, In0P->sock_type, In0P->protocol, &OutP->sock.name);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(26100, "socket_create")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_bind_t__defined)
#define __MIG_check__Request__socket_bind_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_bind_t(__attribute__((__unused__)) __Request__socket_bind_t *In0P)
{

	typedef __Request__socket_bind_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_bind_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_bind */
mig_internal novalue _Xsocket_bind
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		sockaddr_t addr;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_bind_t Reply __attribute__((unused));
	typedef __Request__socket_bind_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_bind_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_bind_t__defined */

	__DeclareRcvRpc(26101, "socket_bind")
	__BeforeRcvRpc(26101, "socket_bind")

#if	defined(__MIG_check__Request__socket_bind_t__defined)
	check_result = __MIG_check__Request__socket_bind_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_bind_t__defined) */

	OutP->RetCode = socket_bind(In0P->Head.msgh_request_port, In0P->addr);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(26101, "socket_bind")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_listen_t__defined)
#define __MIG_check__Request__socket_listen_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_listen_t(__attribute__((__unused__)) __Request__socket_listen_t *In0P)
{

	typedef __Request__socket_listen_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_listen_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_listen */
mig_internal novalue _Xsocket_listen
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int backlog;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_listen_t Reply __attribute__((unused));
	typedef __Request__socket_listen_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_listen_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_listen_t__defined */

	__DeclareRcvRpc(26102, "socket_listen")
	__BeforeRcvRpc(26102, "socket_listen")

#if	defined(__MIG_check__Request__socket_listen_t__defined)
	check_result = __MIG_check__Request__socket_listen_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_listen_t__defined) */

	OutP->RetCode = socket_listen(In0P->Head.msgh_request_port, In0P->backlog);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(26102, "socket_listen")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_accept_t__defined)
#define __MIG_check__Request__socket_accept_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_accept_t(__attribute__((__unused__)) __Request__socket_accept_t *In0P)
{

	typedef __Request__socket_accept_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_accept_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_accept */
mig_internal novalue _Xsocket_accept
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_accept_t Reply __attribute__((unused));
	typedef __Request__socket_accept_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_accept_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_accept_t__defined */

#if	UseStaticTemplates
	const static mach_msg_port_descriptor_t connTemplate = {
		/* name = */		MACH_PORT_NULL,
		/* pad1 = */		0,
		/* pad2 = */		0,
		/* disp = */		19,
		/* type = */		MACH_MSG_PORT_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(26103, "socket_accept")
	__BeforeRcvRpc(26103, "socket_accept")

#if	defined(__MIG_check__Request__socket_accept_t__defined)
	check_result = __MIG_check__Request__socket_accept_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_accept_t__defined) */

#if	UseStaticTemplates
	OutP->conn = connTemplate;
#else	/* UseStaticTemplates */
	OutP->conn.disposition = 19;
#if !(defined(KERNEL) && defined(__LP64__))
	OutP->conn.pad1 = 0;
#endif
	OutP->conn.pad2 = 0;
	OutP->conn.type = MACH_MSG_PORT_DESCRIPTOR;
#if defined(KERNEL)
	OutP->conn.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	RetCode = socket_accept(In0P->Head.msgh_request_port, &OutP->conn.name, &OutP->peer_addr);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(26103, "socket_accept")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_connect_t__defined)
#define __MIG_check__Request__socket_connect_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_connect_t(__attribute__((__unused__)) __Request__socket_connect_t *In0P)
{

	typedef __Request__socket_connect_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_connect_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_connect */
mig_internal novalue _Xsocket_connect
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		sockaddr_t addr;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_connect_t Reply __attribute__((unused));
	typedef __Request__socket_connect_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_connect_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_connect_t__defined */

	__DeclareRcvRpc(26104, "socket_connect")
	__BeforeRcvRpc(26104, "socket_connect")

#if	defined(__MIG_check__Request__socket_connect_t__defined)
	check_result = __MIG_check__Request__socket_connect_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_connect_t__defined) */

	OutP->RetCode = socket_connect(In0P->Head.msgh_request_port, In0P->addr);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(26104, "socket_connect")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_send_t__defined)
#define __MIG_check__Request__socket_send_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_send_t(__attribute__((__unused__)) __Request__socket_send_t *In0P)
{

	typedef __Request__socket_send_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->data.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->data.size != In0P->dataCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_send_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_send */
mig_internal novalue _Xsocket_send
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t data;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		mach_msg_type_number_t dataCnt;
		int flags;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_send_t Reply __attribute__((unused));
	typedef __Request__socket_send_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_send_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_send_t__defined */

	__DeclareRcvRpc(26105, "socket_send")
	__BeforeRcvRpc(26105, "socket_send")

#if	defined(__MIG_check__Request__socket_send_t__defined)
	check_result = __MIG_check__Request__socket_send_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_send_t__defined) */

	OutP->RetCode = socket_send(In0P->Head.msgh_request_port, (data_t)(In0P->data.address), In0P->data.size, In0P->flags, &OutP->amount);
	mig_deallocate((vm_offset_t) In0P->data.address, In0P->data.size);
	In0P->data.address = (void *) 0;
	In0P->data.size = (mach_msg_size_t) 0;
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(26105, "socket_send")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_recv_t__defined)
#define __MIG_check__Request__socket_recv_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_recv_t(__attribute__((__unused__)) __Request__socket_recv_t *In0P)
{

	typedef __Request__socket_recv_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_recv_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_recv */
mig_internal novalue _Xsocket_recv
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int flags;
		int amount;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_recv_t Reply __attribute__((unused));
	typedef __Request__socket_recv_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_recv_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_recv_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t dataTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(26106, "socket_recv")
	__BeforeRcvRpc(26106, "socket_recv")

#if	defined(__MIG_check__Request__socket_recv_t__defined)
	check_result = __MIG_check__Request__socket_recv_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_recv_t__defined) */

#if	UseStaticTemplates
	OutP->data = dataTemplate;
#else	/* UseStaticTemplates */
	OutP->data.deallocate =  FALSE;
	OutP->data.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->data.pad1 = 0;
	OutP->data.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->data.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->dataCnt = 0;

	RetCode = socket_recv(In0P->Head.msgh_request_port, (data_t *)&(OutP->data.address), &OutP->dataCnt, In0P->flags, In0P->amount);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->data.size = OutP->dataCnt;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(26106, "socket_recv")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_name_t__defined)
#define __MIG_check__Request__socket_name_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_name_t(__attribute__((__unused__)) __Request__socket_name_t *In0P)
{

	typedef __Request__socket_name_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_name_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_name */
mig_internal novalue _Xsocket_name
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_name_t Reply __attribute__((unused));
	typedef __Request__socket_name_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_name_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_name_t__defined */

	__DeclareRcvRpc(26107, "socket_name")
	__BeforeRcvRpc(26107, "socket_name")

#if	defined(__MIG_check__Request__socket_name_t__defined)
	check_result = __MIG_check__Request__socket_name_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_name_t__defined) */

	OutP->RetCode = socket_name(In0P->Head.msgh_request_port, &OutP->addr);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(26107, "socket_name")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_peername_t__defined)
#define __MIG_check__Request__socket_peername_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_peername_t(__attribute__((__unused__)) __Request__socket_peername_t *In0P)
{

	typedef __Request__socket_peername_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_peername_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_peername */
mig_internal novalue _Xsocket_peername
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_peername_t Reply __attribute__((unused));
	typedef __Request__socket_peername_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_peername_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_peername_t__defined */

	__DeclareRcvRpc(26108, "socket_peername")
	__BeforeRcvRpc(26108, "socket_peername")

#if	defined(__MIG_check__Request__socket_peername_t__defined)
	check_result = __MIG_check__Request__socket_peername_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_peername_t__defined) */

	OutP->RetCode = socket_peername(In0P->Head.msgh_request_port, &OutP->addr);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(26108, "socket_peername")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_shutdown_t__defined)
#define __MIG_check__Request__socket_shutdown_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_shutdown_t(__attribute__((__unused__)) __Request__socket_shutdown_t *In0P)
{

	typedef __Request__socket_shutdown_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_shutdown_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_shutdown */
mig_internal novalue _Xsocket_shutdown
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int how;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_shutdown_t Reply __attribute__((unused));
	typedef __Request__socket_shutdown_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_shutdown_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_shutdown_t__defined */

	__DeclareRcvRpc(26109, "socket_shutdown")
	__BeforeRcvRpc(26109, "socket_shutdown")

#if	defined(__MIG_check__Request__socket_shutdown_t__defined)
	check_result = __MIG_check__Request__socket_shutdown_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_shutdown_t__defined) */

	OutP->RetCode = socket_shutdown(In0P->Head.msgh_request_port, In0P->how);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(26109, "socket_shutdown")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_getopt_t__defined)
#define __MIG_check__Request__socket_getopt_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_getopt_t(__attribute__((__unused__)) __Request__socket_getopt_t *In0P)
{

	typedef __Request__socket_getopt_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_getopt_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_getopt */
mig_internal novalue _Xsocket_getopt
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		int level;
		int option;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_getopt_t Reply __attribute__((unused));
	typedef __Request__socket_getopt_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_getopt_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_getopt_t__defined */

#if	UseStaticTemplates
	const static mach_msg_ool_descriptor_t optvalTemplate = {
		/* addr = */		(void *)0,
		/* size = */		0,
		/* deal = */		FALSE,
		/* copy = */		MACH_MSG_VIRTUAL_COPY,
		/* pad2 = */		0,
		/* type = */		MACH_MSG_OOL_DESCRIPTOR,
	};
#endif	/* UseStaticTemplates */

	kern_return_t RetCode;
	__DeclareRcvRpc(26110, "socket_getopt")
	__BeforeRcvRpc(26110, "socket_getopt")

#if	defined(__MIG_check__Request__socket_getopt_t__defined)
	check_result = __MIG_check__Request__socket_getopt_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_getopt_t__defined) */

#if	UseStaticTemplates
	OutP->optval = optvalTemplate;
#else	/* UseStaticTemplates */
	OutP->optval.deallocate =  FALSE;
	OutP->optval.copy = MACH_MSG_VIRTUAL_COPY;
	OutP->optval.pad1 = 0;
	OutP->optval.type = MACH_MSG_OOL_DESCRIPTOR;
#if defined(KERNEL) && !defined(__LP64__)
	OutP->optval.pad_end = 0;
#endif
#endif	/* UseStaticTemplates */


	OutP->optvalCnt = 0;

	RetCode = socket_getopt(In0P->Head.msgh_request_port, In0P->level, In0P->option, (data_t *)&(OutP->optval.address), &OutP->optvalCnt);
	if (RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, RetCode);
	}
	OutP->optval.size = OutP->optvalCnt;


	OutP->NDR = NDR_record;


	OutP->Head.msgh_bits |= MACH_MSGH_BITS_COMPLEX;
	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	OutP->msgh_body.msgh_descriptor_count = 1;
	__AfterRcvRpc(26110, "socket_getopt")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__socket_subsystem__
#if !defined(__MIG_check__Request__socket_setopt_t__defined)
#define __MIG_check__Request__socket_setopt_t__defined

mig_internal kern_return_t __MIG_check__Request__socket_setopt_t(__attribute__((__unused__)) __Request__socket_setopt_t *In0P)
{

	typedef __Request__socket_setopt_t __Request;
#if	__MigTypeCheck
	if (!(In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->msgh_body.msgh_descriptor_count != 1) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

#if	__MigTypeCheck
	if (In0P->optval.type != MACH_MSG_OOL_DESCRIPTOR)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

#if __MigTypeCheck
	if (In0P->optval.size != In0P->optvalCnt)
		return MIG_TYPE_ERROR;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__socket_setopt_t__defined) */
#endif /* __MIG_check__Request__socket_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine socket_setopt */
mig_internal novalue _Xsocket_setopt
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		/* start of the kernel processed data */
		mach_msg_body_t msgh_body;
		mach_msg_ool_descriptor_t optval;
		/* end of the kernel processed data */
		NDR_record_t NDR;
		int level;
		int option;
		mach_msg_type_number_t optvalCnt;
		mach_msg_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Reply__socket_setopt_t Reply __attribute__((unused));
	typedef __Request__socket_setopt_t __Request __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
#ifdef	__MIG_check__Request__socket_setopt_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__socket_setopt_t__defined */

	__DeclareRcvRpc(26111, "socket_setopt")
	__BeforeRcvRpc(26111, "socket_setopt")

#if	defined(__MIG_check__Request__socket_setopt_t__defined)
	check_result = __MIG_check__Request__socket_setopt_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__socket_setopt_t__defined) */

	OutP->RetCode = socket_setopt(In0P->Head.msgh_request_port, In0P->level, In0P->option, (data_t)(In0P->optval.address), In0P->optval.size);
	mig_deallocate((vm_offset_t) In0P->optval.address, In0P->optval.size);
	In0P->optval.address = (void *) 0;
	In0P->optval.size = (mach_msg_size_t) 0;

	OutP->NDR = NDR_record;


	__AfterRcvRpc(26111, "socket_setopt")
}



/* Description of this subsystem, for use in direct RPC */
const struct socket_subsystem socket_subsystem = {
	socket_server_routine,
	26100,
	26112,
	(mach_msg_size_t)sizeof(union __ReplyUnion__socket_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_create, 4, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_create_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_bind, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_bind_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_listen, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_listen_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_accept, 3, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_accept_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_connect, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_connect_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_send, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_send_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_recv, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_recv_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_name, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_name_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_peername, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_peername_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_shutdown, 2, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_shutdown_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_getopt, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_getopt_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xsocket_setopt, 5, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__socket_setopt_t)},
	}
};

mig_external boolean_t socket_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 26111) || (InHeadP->msgh_id < 26100) ||
	    ((routine = socket_subsystem.routine[InHeadP->msgh_id - 26100].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t socket_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 26100;

	if ((msgh_id > 11) || (msgh_id < 0))
		return 0;

	return socket_subsystem.routine[msgh_id].stub_routine;
}
